import { useMemo, useState } from 'react';
import {
  Plus, X, Trash2, Search, ArrowUp, ArrowDown, Zap, Coins, Wrench, Package,
  Gauge, Truck, Repeat, HandCoins, Ban, Sparkles, Factory
} from 'lucide-react';
import { useEntityStore, makeModifier } from '../../stores/useEntityStore';
import { Library, Pencil } from 'lucide-react';
import {
  KEYWORD, KEYWORDS, WHEN, getKeyword, paletteForKeyword, makeStatement,
  renderStatement, statementsOf,
  MODIFIER_BUCKETS, bucketsFor, TARGET_MODES, getPaletteEntry, MODIFIER_SHAPES,
  TRIGGER_EVENTS, getTriggerEvent, clampModifierValue, describeModifierDirection,
  RESTRICTION_KINDS, getRestrictionKind, blankRestriction, AUTHORABLE_STATUSES,
  skillsByLayer, DEFAULT_STATEMENT_CHARGE_DELTA,
  effectRefsOf, expandBearer, rulesLinesOf,
  chargeMomentsFor, chargeMomentOf, getChargeMoment, DEFAULT_CHARGE_DELTA_BY_MOMENT,
  scaleStatement, effectTitle, MAX_SCALE,
  REACH, REACHES, DEFAULT_REACH,
} from '../../utils/constants';
import { Field } from '../shared/EditorLayout';
import InlineItemModal from '../shared/InlineItemModal';

/**
 * The Rules editor — a Token's statements, one sentence per row.
 *
 * ## What this replaced
 * `EffectBlocks.jsx`: 1,080 lines in which five unrelated mechanics — target,
 * capability provision, trigger, upkeep and a *list* of modifiers — shared one
 * container, all five visible on every block whether or not they applied. About
 * 490 of those lines were that crowding, and another 190 were four separate
 * hand-rolled item pickers.
 *
 * Here a row shows only what its keyword needs, and there is one item picker.
 *
 * ## The row IS the sentence
 * Every row ends with its own rules text, generated by the same function the
 * game's tooltip uses. That is the validation: if the sentence says something
 * you did not mean, the rule says something you did not mean. A flipped sign
 * reads "5% **more** work time"; a tag typo reads "adjacent **Coste** Tokens".
 *
 * ## ⚠️ Requires is a view of `acceptedTokens`, not a statement
 * Owner decision Q5. That field gates whether a station produces anything at
 * all — `RecipeResolver.checkAcceptedTokens` is the highest-consequence reader
 * in the system — so it stays exactly where it is and only its presentation
 * moves into this list. The author sees one unified set of sentences; the
 * engine sees no change whatsoever.
 */

const KEYWORD_ICON = {
  [KEYWORD.PROVIDES]: Gauge,
  [KEYWORD.GRANTS]: HandCoins,
  [KEYWORD.ACTS_AS]: Wrench,
  [KEYWORD.REQUIRES]: Package,
  [KEYWORD.RESTOCKS]: Truck,
  [KEYWORD.CONVERTS]: Repeat,
  [KEYWORD.CANNOT]: Ban,
  [KEYWORD.APPLIES]: Sparkles,
  [KEYWORD.STATION]: Factory,
};

/**
 * The statement rows for ONE library entry.
 *
 * Bearer-agnostic on purpose: an entry is a name and a list of sentences, and
 * nothing about editing that list depends on whether a Token or an item ends up
 * referencing it. `Requires` is deliberately absent from the add menu — it is a
 * view of a Token's own `acceptedTokens` field (owner Q5), which is a property
 * of that Token and not something a shared effect could carry.
 */
export function StatementList({ statements, onChange }) {
  const tokens = useEntityStore((s) => s.tokens);
  const items = useEntityStore((s) => s.items);
  const [menuOpen, setMenuOpen] = useState(false);

  const list = statements || [];
  const patch = (id, changes) =>
    onChange(list.map((st) => (st.id === id ? { ...st, ...changes } : st)));
  const remove = (id) => onChange(list.filter((st) => st.id !== id));
  const move = (id, by) => {
    const from = list.findIndex((st) => st.id === id);
    const to = from + by;
    if (from < 0 || to < 0 || to >= list.length) return;
    const next = [...list];
    const [row] = next.splice(from, 1);
    next.splice(to, 0, row);
    onChange(next);
  };

  const names = useMemo(() => ({
    token: (id) => tokens[id]?.name || id,
    item: (id) => items[id]?.name || id,
  }), [tokens, items]);

  return (
    <div className="space-y-3">
      {list.length === 0 && (
        <p className="text-[11px] leading-relaxed" style={{ color: 'var(--color-warning)' }}>
          This effect has a name and nothing behind it. A named effect must carry
          at least one rule — add one below, or delete the effect.
        </p>
      )}

      {list.map((statement, i) => (
        <StatementRow
          key={statement.id}
          statement={statement}
          tokens={tokens}
          items={items}
          names={names}
          canMoveUp={i > 0}
          canMoveDown={i < list.length - 1}
          onMove={(by) => move(statement.id, by)}
          onChange={(changes) => patch(statement.id, changes)}
          onRemove={() => remove(statement.id)}
        />
      ))}

      <div className="pt-1">
        {menuOpen ? (
          <div className="rounded-lg border border-white/10 bg-black/30 p-2 space-y-1">
            {KEYWORDS.filter((k) => k.id !== KEYWORD.REQUIRES).map((k) => {
              const Icon = KEYWORD_ICON[k.id] || Zap;
              return (
                <button
                  key={k.id}
                  onClick={() => { setMenuOpen(false); onChange([...list, makeStatement(k.id)]); }}
                  className="w-full text-left flex items-start gap-2 px-2 py-1.5 rounded hover:bg-white/5"
                  style={{ background: 'transparent', border: 'none', cursor: 'pointer' }}
                >
                  <Icon size={13} className="text-emerald-400 mt-0.5 flex-shrink-0" />
                  <span className="flex-1">
                    <span className="block text-xs text-gray-200 font-medium">{k.label}</span>
                    <span className="block text-[10px] text-gray-500 leading-snug">{k.blurb}</span>
                  </span>
                </button>
              );
            })}
            <button
              onClick={() => setMenuOpen(false)}
              className="w-full text-center text-[10px] text-gray-500 py-1"
              style={{ background: 'transparent', border: 'none', cursor: 'pointer' }}
            >
              cancel
            </button>
          </div>
        ) : (
          <button
            onClick={() => setMenuOpen(true)}
            className="flex items-center gap-1 px-2.5 py-1.5 rounded text-[11px]"
            style={{ background: 'var(--color-accent-muted)', color: 'var(--color-accent-hover)', border: 'none', cursor: 'pointer' }}
          >
            <Plus size={12} /> Add rule
          </button>
        )}
      </div>
    </div>
  );
}

/**
 * A Token's rules: its requirements, and the library entries it references.
 *
 * ## ⚠️ The rules are NOT edited here any more (Unified Effects P1)
 * A Token points at named effects, and an effect can be pointed at by several
 * Tokens and — from P4 — by items. Editing a sentence in place on one Token
 * would change it everywhere while looking local, which is the one way this
 * feature could hurt. So a row here shows the effect's name and its sentences
 * read-only, with the reference count that says how far an edit reaches, and
 * "Edit" opens the entry itself.
 *
 * `Requires` stays a Token field and stays editable here — it is
 * `acceptedTokens`, which gates whether the station produces anything at all.
 */
export default function Statements({ token, item }) {
  // One component, either bearer (Unified Effects P4). The rules half is
  // identical for a Token and an item — a named effect referenced by id, shown
  // with its sentences and its reference count. What differs is `Requires`,
  // which is a Token field (`acceptedTokens`, owner Q5) and has no meaning on
  // something a hero carries.
  const record = token || item;
  const collectionKey = token ? 'tokens' : 'items';
  const effects = useEntityStore((s) => s.effects);
  const tokens = useEntityStore((s) => s.tokens);
  const items = useEntityStore((s) => s.items);
  const updateToken = useEntityStore((s) => s.updateToken);
  const addEffectForBearer = useEntityStore((s) => s.addEffectForBearer);
  const addEffectRef = useEntityStore((s) => s.addEffectRef);
  const removeEffectRef = useEntityStore((s) => s.removeEffectRef);
  const setEffectRefScale = useEntityStore((s) => s.setEffectRefScale);
  const setActiveEntity = useEntityStore((s) => s.setActiveEntity);

  const [menuOpen, setMenuOpen] = useState(false);
  const [browsing, setBrowsing] = useState(false);
  const [search, setSearch] = useState('');

  const requirements = token ? (token.acceptedTokens || []) : [];
  const refs = effectRefsOf(record);
  const setRequirements = (next) => updateToken(record.id, { acceptedTokens: next });

  const names = useMemo(() => ({
    token: (id) => tokens[id]?.name || id,
    item: (id) => items[id]?.name || id,
  }), [tokens, items]);

  /**
   * How many bearers use an entry — the number that makes an edit legible.
   * Counts Tokens AND items: an effect shared between a Bay and a potion is
   * exactly the case the library exists for, and an edit reaches both.
   */
  const bearerCount = (effectId) =>
    [...Object.values(tokens), ...Object.values(items)]
      .filter((b) => effectRefsOf(b).some((r) => r.effectId === effectId)).length;

  const unused = Object.values(effects)
    .filter((e) => !refs.some((r) => r.effectId === e.id))
    .filter((e) => !search || (e.name || '').toLowerCase().includes(search.toLowerCase()));

  const isEmpty = refs.length === 0 && requirements.length === 0;

  if (!record) return null;

  return (
    <div className="space-y-3">
      {isEmpty && (
        <p className="text-[11px] text-gray-500 leading-relaxed">
          {token
            ? 'No rules. A pure producer needs none — rules are for Tokens that change what happens around them, hand a capability to a neighbour, or need one themselves.'
            : 'No rules. Most items need none — rules are for gear and consumables that change what their hero does: the Token they are working, the enemy they are fighting, or the hero themselves.'}
        </p>
      )}

      {token?.effectBlocks?.length > 0 && (
        <div
          className="rounded-lg p-3 text-[11px] leading-relaxed"
          style={{ background: 'rgba(255,180,0,0.08)', border: '1px solid rgba(255,180,0,0.3)', color: 'var(--color-warning)' }}
        >
          This Token still carries <strong>effect blocks</strong> from the old
          editor. They are not read by the game any more, so it currently does
          nothing. Rebuild its rules below — adding the first rule clears the old
          data for good.
        </div>
      )}

      {requirements.map((req, i) => (
        <RequiresRow
          key={`req_${i}`}
          requirement={req}
          tokens={tokens}
          names={names}
          onChange={(next) => setRequirements(requirements.map((r, idx) => (idx === i ? next : r)))}
          onRemove={() => setRequirements(requirements.filter((_, idx) => idx !== i))}
        />
      ))}

      {refs.map(({ effectId, scale }) => {
        const entry = effects[effectId];

        if (!entry) {
          return (
            <div
              key={effectId}
              className="rounded-lg p-3 text-[11px] leading-relaxed flex items-center gap-2"
              style={{ background: 'rgba(255,80,80,0.08)', border: '1px solid rgba(255,80,80,0.3)', color: '#f87171' }}
            >
              <span className="flex-1">
                This Token points at the effect <strong>{effectId}</strong>, which no
                longer exists. It currently has no rule from it.
              </span>
              <button
                onClick={() => removeEffectRef(collectionKey, record.id, effectId)}
                className="btn-ghost" style={{ padding: '2px 6px' }}
              >
                <Trash2 size={12} />
              </button>
            </div>
          );
        }

        // Scalable when at least one of its statements declares a field a scale
        // touches — the palette for a Provides/Grants/Converts payload, the
        // keyword itself for Applies (UE-7).
        const scalable = (entry.statements || []).some((st) =>
          getPaletteEntry(st?.payload?.type)?.scales || getKeyword(st?.keyword)?.scales
        );
        const count = bearerCount(effectId);
        /**
         * ⚠️ The sentences are rendered from the **scaled** statements, not the
         * entry's own. A row showing "5% less work time" beside a scale of 3 is
         * the drift UE-8 exists to prevent — the words have to say what this
         * bearer actually does, which is 15%.
         */
        const lines = rulesLinesOf(
          { statements: (entry.statements || []).map((st) => scaleStatement(st, scale)) },
          names
        );

        return (
          <div key={effectId} className="rounded-lg border border-white/10 bg-black/20">
            <div className="flex items-center gap-2 px-3 py-2 border-b border-white/5">
              <Library size={13} className="text-emerald-400" />
              <span className="text-xs font-medium text-gray-200">{effectTitle(entry.name, scale)}</span>
              {count > 1 && (
                <span
                  className="text-[10px] px-1.5 py-0.5 rounded"
                  style={{ background: 'var(--color-accent-muted)', color: 'var(--color-accent-hover)' }}
                  title={`Shared with ${count - 1} other Token${count > 2 ? 's' : ''} — editing it changes all of them`}
                >
                  shared x{count}
                </span>
              )}
              <span className="flex-1" />
              {/*
                Scale lives on the REFERENCE (UE-6): the one thing a bearer may
                vary about a shared effect. Offered only where the effect has
                something to scale — `Acts as` and `Cannot` declare nothing, and
                a spinner that changed no number would be a lie.
              */}
              {scalable && (
                <label className="flex items-center gap-1 text-[10px] text-gray-500" title="How strong this Token's version is. 1-5; the entry itself is unchanged.">
                  x
                  <input
                    type="number"
                    min={1}
                    max={MAX_SCALE}
                    step={1}
                    value={scale}
                    onChange={(e) => setEffectRefScale(collectionKey, record.id, effectId, e.target.value)}
                    className="w-11"
                    style={{ fontSize: 10, padding: '1px 4px' }}
                  />
                </label>
              )}
              <button
                onClick={() => setActiveEntity(effectId, 'effect')}
                className="btn-ghost flex items-center gap-1 text-[10px]"
                style={{ padding: '2px 6px' }}
                title="Open this effect"
              >
                <Pencil size={11} /> Edit
              </button>
              <button
                onClick={() => removeEffectRef(collectionKey, record.id, effectId)}
                className="btn-ghost" style={{ padding: '2px 6px' }}
                title="Stop this Token using the effect (the effect itself is kept)"
              >
                <X size={12} />
              </button>
            </div>
            <div className="px-3 py-2 space-y-1">
              {lines.length === 0 ? (
                <p className="text-[11px] italic" style={{ color: 'var(--color-warning)' }}>
                  This effect has no rule behind it.
                </p>
              ) : lines.map((line, i) => (
                <p key={i} className="text-[11px] text-gray-400 leading-relaxed">{line}</p>
              ))}
            </div>
          </div>
        );
      })}

      <div className="pt-1 space-y-2">
        {browsing && (
          <div className="rounded-lg border border-white/10 bg-black/30 p-2 space-y-1">
            <div className="flex items-center gap-1.5 px-1 pb-1">
              <Search size={12} className="text-gray-500" />
              <input
                autoFocus
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                placeholder="Search effects..."
                className="flex-1 bg-transparent text-xs text-gray-200 outline-none"
              />
            </div>
            {unused.length === 0 ? (
              <p className="text-[10px] text-gray-600 px-2 py-1">No other effects to add.</p>
            ) : unused.map((e) => (
              <button
                key={e.id}
                onClick={() => { setBrowsing(false); setSearch(''); addEffectRef(collectionKey, record.id, e.id); }}
                className="w-full text-left flex items-start gap-2 px-2 py-1.5 rounded hover:bg-white/5"
                style={{ background: 'transparent', border: 'none', cursor: 'pointer' }}
              >
                <Library size={12} className="text-emerald-400 mt-0.5 flex-shrink-0" />
                <span className="flex-1">
                  <span className="block text-xs text-gray-200 font-medium">{e.name}</span>
                  <span className="block text-[10px] text-gray-500 leading-snug">
                    {rulesLinesOf(e, names)[0] || 'No rule behind it yet.'}
                  </span>
                </span>
                <span className="text-[10px] text-gray-600 mt-0.5">
                  {bearerCount(e.id) > 0 ? `used x${bearerCount(e.id)}` : 'unused'}
                </span>
              </button>
            ))}
            <button
              onClick={() => { setBrowsing(false); setSearch(''); }}
              className="w-full text-center text-[10px] text-gray-500 py-1"
              style={{ background: 'transparent', border: 'none', cursor: 'pointer' }}
            >
              cancel
            </button>
          </div>
        )}

        {menuOpen ? (
          <div className="rounded-lg border border-white/10 bg-black/30 p-2 space-y-1">
            {KEYWORDS.filter((k) => token || k.id !== KEYWORD.REQUIRES).map((k) => {
              const Icon = KEYWORD_ICON[k.id] || Zap;
              return (
                <button
                  key={k.id}
                  onClick={() => {
                    setMenuOpen(false);
                    // Requires is a Token field, not a shared effect (owner Q5).
                    if (k.id === KEYWORD.REQUIRES) {
                      setRequirements([...requirements, { tag: '', minTier: 1 }]);
                      return;
                    }
                    addEffectForBearer(collectionKey, record.id, k.id);
                  }}
                  className="w-full text-left flex items-start gap-2 px-2 py-1.5 rounded hover:bg-white/5"
                  style={{ background: 'transparent', border: 'none', cursor: 'pointer' }}
                >
                  <Icon size={13} className="text-emerald-400 mt-0.5 flex-shrink-0" />
                  <span className="flex-1">
                    <span className="block text-xs text-gray-200 font-medium">{k.label}</span>
                    <span className="block text-[10px] text-gray-500 leading-snug">{k.blurb}</span>
                  </span>
                </button>
              );
            })}
            <button
              onClick={() => setMenuOpen(false)}
              className="w-full text-center text-[10px] text-gray-500 py-1"
              style={{ background: 'transparent', border: 'none', cursor: 'pointer' }}
            >
              cancel
            </button>
          </div>
        ) : (
          <div className="flex gap-2">
            <button
              onClick={() => setMenuOpen(true)}
              className="flex items-center gap-1 px-2.5 py-1.5 rounded text-[11px]"
              style={{ background: 'var(--color-accent-muted)', color: 'var(--color-accent-hover)', border: 'none', cursor: 'pointer' }}
            >
              <Plus size={12} /> New rule
            </button>
            <button
              onClick={() => setBrowsing(true)}
              className="flex items-center gap-1 px-2.5 py-1.5 rounded text-[11px] btn-ghost"
            >
              <Library size={12} /> Use an existing effect
            </button>
          </div>
        )}
      </div>
    </div>
  );
}

/** One row's chrome: keyword name, reorder, delete, and the sentence. */
function RowShell({ keywordId, sentence, onMove, canMoveUp, canMoveDown, onRemove, children }) {
  const keyword = getKeyword(keywordId);
  const Icon = KEYWORD_ICON[keywordId] || Zap;
  return (
    <div className="rounded-lg border border-white/10 bg-black/20">
      <div className="flex items-center gap-2 px-3 py-2 border-b border-white/5">
        <Icon size={13} className="text-emerald-400" />
        <span className="text-xs font-medium text-gray-200">{keyword?.label || keywordId}</span>
        <span className="flex-1" />
        {onMove && (
          <>
            <button
              onClick={() => onMove(-1)}
              disabled={!canMoveUp}
              className="text-gray-600 hover:text-gray-300 disabled:opacity-20"
              style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 0, lineHeight: 0 }}
              title="Move up"
            >
              <ArrowUp size={12} />
            </button>
            <button
              onClick={() => onMove(1)}
              disabled={!canMoveDown}
              className="text-gray-600 hover:text-gray-300 disabled:opacity-20"
              style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 0, lineHeight: 0 }}
              title="Move down"
            >
              <ArrowDown size={12} />
            </button>
          </>
        )}
        <button
          onClick={onRemove}
          className="text-gray-600 hover:text-red-400"
          style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 0, lineHeight: 0 }}
          title="Remove rule"
        >
          <Trash2 size={12} />
        </button>
      </div>

      <div className="p-3 space-y-2.5">{children}</div>

      <p className="px-3 py-2 border-t border-white/5 text-[11px] italic text-emerald-300/90 leading-relaxed">
        “{sentence}”
      </p>
    </div>
  );
}

/** Requires — a view of the top-level `acceptedTokens` field (owner Q5). */
function RequiresRow({ requirement, tokens, names, onChange, onRemove }) {
  const capabilities = useCapabilityVocabulary(tokens);
  const effects = useEntityStore((s) => s.effects);
  const sentence = renderStatement(
    { keyword: KEYWORD.REQUIRES, payload: requirement }, names
  );
  // Expanded: an `Acts as` rule lives in the library, so an unexpanded Token
  // provides nothing and this list would always read "nothing supplies this".
  const providers = Object.values(tokens).filter((t) =>
    providedTagsOf(expandBearer(t, effects || {}))
      .some((p) => p.tag === requirement.tag && (p.tier || 1) >= (requirement.minTier || 1))
  );

  return (
    <RowShell keywordId={KEYWORD.REQUIRES} sentence={sentence} onRemove={onRemove}>
      <div className="flex gap-3">
        <Field label="Capability" className="flex-1">
          <input
            type="text"
            list="cms-capability-tags"
            value={requirement.tag || ''}
            placeholder="e.g. pickaxe"
            onChange={(e) => onChange({ ...requirement, tag: e.target.value.trim().toLowerCase() })}
            className="w-full"
            style={{ fontSize: 12 }}
          />
        </Field>
        <Field label="Min Tool Tier" className="w-28">
          <input
            type="number"
            min={1}
            value={requirement.minTier ?? 1}
            onChange={(e) => onChange({ ...requirement, minTier: Math.max(1, Number(e.target.value)) })}
            className="w-full"
            style={{ fontSize: 12 }}
          />
        </Field>
      </div>
      <CapabilityDatalist capabilities={capabilities} />
      <p className="text-[10px] text-gray-500">
        Satisfied by:{' '}
        {providers.length === 0 ? (
          <span className="text-amber-400">nothing yet — this Token can never work</span>
        ) : (
          providers.map((t) => t.name).join(', ')
        )}
      </p>
    </RowShell>
  );
}

/** One real statement. */
function StatementRow({ statement, tokens, items, names, onChange, onRemove, onMove, canMoveUp, canMoveDown }) {
  const keyword = getKeyword(statement.keyword);
  const sentence = renderStatement(statement, names);

  return (
    <RowShell
      keywordId={statement.keyword}
      sentence={sentence}
      onRemove={onRemove}
      onMove={onMove}
      canMoveUp={canMoveUp}
      canMoveDown={canMoveDown}
    >
      <PayloadFields statement={statement} tokens={tokens} items={items} onChange={onChange} />

      {keyword?.reach && <ReachPicker statement={statement} onChange={onChange} />}

      {keyword?.filter && (
        <FilterPicker
          statement={statement}
          tokens={tokens}
          onChange={onChange}
          // The same filter, asked three different ways round. "Reaches" is
          // wrong in front of a restriction and wrong in front of a status, and
          // a label that reads wrong is how an author picks the wrong thing.
          label={
            statement.keyword === KEYWORD.CANNOT ? 'Too many of what'
              : statement.keyword === KEYWORD.APPLIES ? 'Heroes working'
                : statement.keyword === KEYWORD.CONVERTS ? 'Output goes to'
                  : 'Reaches'
          }
          // ⚠️ A conversion picks ONE destination, not a set (ER-14), so the
          // "every Token nearby" hint below would promise a broadcast the
          // runtime deliberately refuses to do.
          singleTarget={statement.keyword === KEYWORD.CONVERTS}
        />
      )}

      {keyword?.when !== WHEN.NEVER && (
        <TriggerClause statement={statement} tokens={tokens} items={items} onChange={onChange} />
      )}

      {/*
        ⚠️ Outside the trigger gate since UE-20. Firing used to be the only
        moment anything spent at, so the cost only made sense beside a trigger.
        The moment is authored now — an always-on aura can be made to cost its
        Token a charge per cycle, and the free case is a written 0.
      */}
      <ChargeClause statement={statement} onChange={onChange} />

      {keyword?.upkeep && <UpkeepClause statement={statement} items={items} onChange={onChange} />}
    </RowShell>
  );
}

/** The payload — different for every keyword, and only ever one thing. */
function PayloadFields({ statement, tokens, items, onChange }) {
  const payload = statement.payload || {};
  const setPayload = (changes) => onChange({ payload: { ...payload, ...changes } });

  switch (statement.keyword) {
    case KEYWORD.PROVIDES:
      return <EffectFields statement={statement} onChange={onChange} />;

    case KEYWORD.GRANTS:
      return (
        <div className="flex gap-3 items-end">
          <ItemPicker
            label="Item"
            value={payload.itemId}
            items={items}
            onPick={(itemId) => setPayload({ itemId })}
            className="flex-1"
          />
          <Field label="How many" className="w-24">
            <input
              type="number" min={1} value={payload.quantity ?? 1}
              onChange={(e) => setPayload({ quantity: Math.max(1, Number(e.target.value)) })}
              className="w-full" style={{ fontSize: 12 }}
            />
          </Field>
          <Field label="Chance %" className="w-24">
            <input
              type="number" min={1} max={100} value={payload.chance ?? 100}
              onChange={(e) => setPayload({ chance: Math.min(100, Math.max(1, Number(e.target.value))) })}
              className="w-full" style={{ fontSize: 12 }}
            />
          </Field>
        </div>
      );

    case KEYWORD.STATION:
      return <StationFields payload={payload} setPayload={setPayload} />;

    case KEYWORD.ACTS_AS:
      return <ActsAsFields payload={payload} tokens={tokens} setPayload={setPayload} />;

    case KEYWORD.RESTOCKS:
      return <RestocksFields payload={payload} tokens={tokens} setPayload={setPayload} />;

    case KEYWORD.CANNOT:
      return <CannotFields payload={payload} setPayload={setPayload} onChange={onChange} />;

    case KEYWORD.APPLIES:
      return <AppliesFields payload={payload} setPayload={setPayload} />;

    case KEYWORD.CONVERTS:
      return (
        <div className="grid grid-cols-2 gap-3">
          <ItemList
            label="Spends from the Bank"
            entries={payload.consumes || []}
            items={items}
            onChange={(consumes) => setPayload({ consumes })}
          />
          <ItemList
            label="Produces on the board"
            entries={payload.produces || []}
            items={items}
            onChange={(produces) => setPayload({ produces })}
          />
        </div>
      );

    default:
      return null;
  }
}

/**
 * The one field a Station statement has: which skill's recipes it can run.
 *
 * The list comes from the game's `skillRegistry` (via `constants.js`), so the
 * CMS can never offer a skill the game has not heard of — the drift CMS-5
 * exists to prevent, and the exact failure that produced `industry` and
 * `culinary` in the old content.
 */
function StationFields({ payload, setPayload }) {
  return (
    <div className="flex gap-3">
      <Field label="Skill" className="w-56">
        <select
          value={payload.skill || ''}
          onChange={(e) => setPayload({ skill: e.target.value })}
          className="w-full"
          style={{ fontSize: 12 }}
        >
          <option value="">Pick a skill…</option>
          {skillsByLayer().map(([label, group]) => (
            <optgroup key={label} label={label}>
              {group.map((s) => (
                <option key={s.id} value={s.id}>{s.name}</option>
              ))}
            </optgroup>
          ))}
        </select>
      </Field>
    </div>
  );
}

/**
 * The number effect, with the **direction trap** designed out.
 *
 * ⚠️ You used to type `-0.05` into a box labelled "Value (−0.05 = 5% less)" on
 * an axis where lower is better, and nothing stopped you typing `0.05` and
 * shipping a curse — which is exactly what happened to the Forge Altar. Here
 * the magnitude is always positive and the **direction is a word**; the palette
 * already knows which axes run backwards (`inverted`), so the sign is derived
 * and the sentence reads back in the words you chose.
 */
function EffectFields({ statement, onChange }) {
  const payload = statement.payload || {};
  const entry = getPaletteEntry(payload.type);
  const palette = paletteForKeyword(KEYWORD.PROVIDES, !!statement.when);
  const isProc = entry?.shape === MODIFIER_SHAPES.PROC;
  const bucket = payload.bucket || 'percentage';
  const direction = describeModifierDirection(entry, payload.value, bucket);

  const magnitude = () => {
    const v = Math.abs(Number(payload.value) || 0);
    return bucket === 'percentage' && !isProc ? Math.round(v * 1000) / 10 : v;
  };

  const writeMagnitude = (raw, sign) => {
    const n = Math.abs(Number(raw) || 0);
    const scaled = bucket === 'percentage' && !isProc ? n / 100 : n;
    onChange({ payload: { ...payload, value: clampModifierValue(entry, scaled * sign) } });
  };

  const sign = Number(payload.value) < 0 ? -1 : 1;

  return (
    <div className="space-y-2">
      <div className="flex gap-3 items-end">
        <Field label="Effect" className="flex-1">
          <select
            value={payload.type || ''}
            onChange={(e) => {
              const next = getPaletteEntry(e.target.value);
              onChange({ payload: makeModifier(e.target.value, next?.shape) });
            }}
            className="w-full"
            style={{ fontSize: 12 }}
          >
            {palette.map((p) => (
              <option key={p.type} value={p.type}>{p.label}</option>
            ))}
          </select>
        </Field>

        {!isProc && (
          <Field label="How it combines" className="w-32">
            <select
              value={bucket}
              onChange={(e) => onChange({ payload: { ...payload, bucket: e.target.value } })}
              className="w-full"
              style={{ fontSize: 12 }}
            >
              {/* The palette says which buckets a row accepts. Combat axes take
                  only `flat`, because the reader sums flats and silently skips
                  the rest — offering a percentage would offer nothing. */}
              {bucketsFor(entry).map((b) => (
                <option key={b} value={b}>
                  {b === 'percentage' ? '5%' : b === 'flat' ? '+5' : '×1.5'}
                </option>
              ))}
            </select>
          </Field>
        )}

        <Field label={isProc ? 'Chance %' : 'Amount'} className="w-24">
          <input
            type="number"
            min={0}
            step={bucket === 'multiplier' ? 0.1 : 1}
            value={magnitude()}
            onChange={(e) => writeMagnitude(e.target.value, sign)}
            className="w-full"
            style={{ fontSize: 12 }}
          />
        </Field>

        {!isProc && bucket !== 'multiplier' && (
          <Field label="Direction" className="w-40">
            <select
              value={sign < 0 ? 'less' : 'more'}
              onChange={(e) => writeMagnitude(magnitude(), e.target.value === 'less' ? -1 : 1)}
              className="w-full"
              style={{ fontSize: 12 }}
            >
              <option value="more">more {entry?.inverted ? '(a penalty)' : '(a buff)'}</option>
              <option value="less">less {entry?.inverted ? '(a buff)' : '(a penalty)'}</option>
            </select>
          </Field>
        )}
      </div>

      {entry?.hint && <p className="text-[10px] text-gray-600 leading-relaxed">{entry.hint}</p>}
      {direction && (
        <p className="text-[10px]" style={{ color: direction.isBuff ? 'var(--color-accent-hover)' : 'var(--color-warning)' }}>
          {direction.text}
        </p>
      )}
    </div>
  );
}

/** Acts as — capability plus **Tool Tier**, which lives on the sentence. */
function ActsAsFields({ payload, tokens, setPayload }) {
  const capabilities = useCapabilityVocabulary(tokens);
  return (
    <div className="space-y-2">
      <div className="flex gap-3">
        <Field label="Capability" className="flex-1">
          <input
            type="text"
            list="cms-capability-tags"
            value={payload.tag || ''}
            placeholder="e.g. pickaxe"
            onChange={(e) => setPayload({ tag: e.target.value.trim().toLowerCase() })}
            className="w-full"
            style={{ fontSize: 12 }}
          />
        </Field>
        <Field label="Tool Tier" className="w-28">
          <input
            type="number" min={1} value={payload.tier ?? 1}
            onChange={(e) => setPayload({ tier: Math.max(1, Number(e.target.value)) })}
            className="w-full" style={{ fontSize: 12 }}
          />
        </Field>
      </div>
      <CapabilityDatalist capabilities={capabilities} />
      <p className="text-[10px] text-gray-600 leading-relaxed">
        A station asking for a Tier 2 tool will not accept a Tier 1 one. This is
        the other end of the same wire as a rule’s <strong>Min Tool Tier</strong>.
      </p>
    </div>
  );
}

/** Restocks — the list of Token types this Manager keeps supplied. */
function RestocksFields({ payload, tokens, setPayload }) {
  const chosen = payload.tokenIds || [];
  return (
    <div className="space-y-2">
      <div className="flex flex-wrap gap-1.5">
        {chosen.length === 0 && <span className="text-[11px] text-gray-600">Nothing yet.</span>}
        {chosen.map((id) => (
          <span key={id} className="inline-flex items-center gap-1 px-2 py-1 rounded-md text-[11px] bg-white/5 border border-white/10 text-gray-300">
            {tokens[id]?.name || id}
            <button
              onClick={() => setPayload({ tokenIds: chosen.filter((x) => x !== id) })}
              className="text-gray-500 hover:text-red-400"
              style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 0, lineHeight: 0 }}
            >
              <X size={10} />
            </button>
          </span>
        ))}
      </div>
      <select
        value=""
        onChange={(e) => e.target.value && setPayload({ tokenIds: [...new Set([...chosen, e.target.value])] })}
        className="w-full"
        style={{ fontSize: 12 }}
      >
        <option value="">— add a Token to restock —</option>
        {Object.values(tokens).map((t) => (
          <option key={t.id} value={t.id}>{t.name}</option>
        ))}
      </select>
      <p className="text-[10px] text-gray-600 leading-relaxed">
        Covers the 8 surrounding tiles and never wears out, but it can only move
        a Token from the Bank — an empty Bank simply means the tile stays bare.
      </p>
    </div>
  );
}

/**
 * Cannot — a restriction kind and its limit.
 *
 * The kind list has exactly one row today (design §1.3). It is still a picker
 * rather than a hardcoded "more than N" form, because that is the difference
 * between adding restriction #2 as a row in a registry and adding it as a
 * rewrite of this component.
 */
function CannotFields({ payload, setPayload, onChange }) {
  const kind = getRestrictionKind(payload.kind);

  return (
    <div className="space-y-2">
      <div className="flex gap-3">
        <Field label="Cannot" className="flex-1">
          <select
            value={payload.kind || ''}
            onChange={(e) => onChange({ payload: blankRestriction(e.target.value) })}
            className="w-full"
            style={{ fontSize: 12 }}
          >
            {RESTRICTION_KINDS.map((k) => (
              <option key={k.id} value={k.id}>{k.label}</option>
            ))}
          </select>
        </Field>
        {payload.kind === 'adjacency_limit' && (
          <Field label="No more than" className="w-28">
            <input
              type="number" min={0} value={payload.max ?? 2}
              onChange={(e) => setPayload({ max: Math.max(0, Number(e.target.value)) })}
              className="w-full" style={{ fontSize: 12 }}
            />
          </Field>
        )}
      </div>
      {kind?.blurb && <p className="text-[10px] text-gray-600 leading-relaxed">{kind.blurb}</p>}
      <p className="text-[10px] text-gray-600 leading-relaxed">
        Breaking this refuses the drop: the Token flies back to wherever it came
        from and the board flashes the reason. Nothing is ever destroyed, and a
        saved board that already breaks the rule sends the offender to the Vault.
      </p>
    </div>
  );
}

/**
 * Applies — a status, and how many stacks of it.
 *
 * ⚠️ **The filter below selects Tokens; the status lands on a person.** The
 * owner ruled that this uses the same filter as every other keyword, so there
 * is one targeting concept in the grammar rather than two — which means the
 * honest reading of "adjacent Coast Tokens" here is *the heroes working them*.
 * The generated sentence says exactly that, in those words.
 */
function AppliesFields({ payload, setPayload }) {
  const status = AUTHORABLE_STATUSES.find((s) => s.id === payload.statusId);

  return (
    <div className="space-y-2">
      <div className="flex gap-3 items-end">
        <Field label="Status" className="flex-1">
          <select
            value={payload.statusId || ''}
            onChange={(e) => setPayload({ statusId: e.target.value })}
            className="w-full"
            style={{ fontSize: 12 }}
          >
            <option value="">— pick a status —</option>
            {AUTHORABLE_STATUSES.map((s) => (
              <option key={s.id} value={s.id}>{s.icon} {s.name}</option>
            ))}
          </select>
        </Field>
        <Field label="Stacks" className="w-24">
          <input
            type="number" min={1} value={payload.stacks ?? 1}
            onChange={(e) => setPayload({ stacks: Math.max(1, Number(e.target.value)) })}
            className="w-full" style={{ fontSize: 12 }}
          />
        </Field>
        <Field label="Chance %" className="w-24">
          <input
            type="number" min={1} max={100} value={payload.chance ?? 100}
            onChange={(e) => setPayload({ chance: Math.min(100, Math.max(1, Number(e.target.value))) })}
            className="w-full" style={{ fontSize: 12 }}
          />
        </Field>
      </div>

      {/*
        ⚠️ The one choice an item-borne rule has (UE-24). An item is carried by
        exactly one hero, so `Provides` and `Grants` have a single honest reading
        and need no filter — but a status could land on either side of a fight,
        and "Applies Poison" alone would be true of two opposite rules.

        Shown on every `Applies`, because an effect entry does not know which
        bearer will reference it. On a Token the field is ignored and the filter
        above decides, which the hint says.
      */}
      <Field label="When carried by an item, it lands on">
        <select
          value={payload.target || 'hero'}
          onChange={(e) => setPayload({ target: e.target.value })}
          className="w-full"
          style={{ fontSize: 12 }}
        >
          <option value="hero">The hero carrying it</option>
          <option value="enemy">The enemy that hero is fighting</option>
        </select>
        <p className="text-[10px] text-gray-600 mt-1 leading-relaxed">
          Ignored when a Token carries this effect — a Token&rsquo;s rule uses the
          filter above instead.
        </p>
      </Field>

      {status && (
        <p
          className="text-[10px] leading-relaxed"
          style={{ color: status.category === 'debuff' ? 'var(--color-warning)' : 'var(--color-accent-hover)' }}
        >
          {status.description}
        </p>
      )}
      {status?.combatOnly && (
        <p className="text-[10px]" style={{ color: 'var(--color-warning)' }}>
          ⚠️ {status.name} clears the moment a fight ends, so it does nothing at
          all on a hero who is working rather than fighting.
        </p>
      )}
    </div>
  );
}

/**
 * **How far** the statement carries (ER-1).
 *
 * ⚠️ Sits ABOVE the filter picker, and the order is the point: reach decides the
 * set of Tokens in range, and the filter then picks from it. Reading them the
 * other way round — "Coast Tokens, on the whole board" — invites the author to
 * think the filter widens the reach, which it never does.
 */
function ReachPicker({ statement, onChange }) {
  const current = REACHES.some((r) => r.id === statement.reach) ? statement.reach : DEFAULT_REACH;
  const declared = REACHES.find((r) => r.id === current);

  return (
    <div className="space-y-1.5">
      <Field label="How far">
        <select
          value={current}
          onChange={(e) => onChange({ reach: e.target.value })}
          className="w-full"
          style={{ fontSize: 12 }}
        >
          {REACHES.map((r) => (
            <option key={r.id} value={r.id}>{r.label}</option>
          ))}
        </select>
      </Field>
      <p className="text-[10px] text-gray-600 leading-relaxed">{declared?.hint}</p>
      {current === REACH.BOARD && (
        <p className="text-[10px]" style={{ color: 'var(--color-warning)' }}>
          ⚠️ This touches every Token you own, and a second copy of this Token
          doubles it. Nothing caps that — keep the number very small.
        </p>
      )}
    </div>
  );
}

/** Which neighbours the statement reaches. */
function FilterPicker({ statement, tokens, onChange, label = 'Reaches', singleTarget = false }) {
  const to = statement.to || { mode: 'all', value: '' };
  const knownTags = useMemo(() => {
    const all = new Set();
    for (const t of Object.values(tokens)) for (const tag of t.tags || []) all.add(tag);
    return [...all].sort();
  }, [tokens]);

  const tagMisses = to.mode === 'tag' && to.value && !knownTags.includes(to.value);
  const nearMiss = tagMisses && knownTags.find((t) => t.toLowerCase() === to.value.toLowerCase());

  return (
    <div className="space-y-1.5">
      <div className="flex gap-3">
        <Field label={label} className="flex-1">
          <select
            value={to.mode}
            onChange={(e) => onChange({ to: { mode: e.target.value, value: '' } })}
            className="w-full"
            style={{ fontSize: 12 }}
          >
            {TARGET_MODES.map((m) => (
              <option key={m.mode} value={m.mode}>{m.label}</option>
            ))}
          </select>
        </Field>

        {to.mode === 'tag' && (
          <Field label="Tag" className="flex-1">
            <input
              type="text"
              list="cms-known-token-tags"
              value={to.value || ''}
              onChange={(e) => onChange({ to: { mode: 'tag', value: e.target.value } })}
              placeholder="e.g. Coast"
              className="w-full"
              style={{ fontSize: 12 }}
            />
            <datalist id="cms-known-token-tags">
              {knownTags.map((t) => <option key={t} value={t} />)}
            </datalist>
          </Field>
        )}

        {to.mode === 'id' && (
          <Field label="Token" className="flex-1">
            <select
              value={to.value || ''}
              onChange={(e) => onChange({ to: { mode: 'id', value: e.target.value } })}
              className="w-full"
              style={{ fontSize: 12 }}
            >
              <option value="">— pick a Token —</option>
              {Object.values(tokens).map((t) => (
                <option key={t.id} value={t.id}>{t.name}</option>
              ))}
            </select>
          </Field>
        )}
      </div>

      {tagMisses && (
        <p className="text-[10px]" style={{ color: 'var(--color-warning)' }}>
          ⚠️ No Token carries the tag “{to.value}”, so this reaches nothing.
          {nearMiss && <> Did you mean <strong>{nearMiss}</strong>? Tags match exactly, including case.</>}
        </p>
      )}
      {to.mode === 'all' && !singleTarget && (
        <p className="text-[10px] text-gray-600 leading-relaxed">
          Every Token on the 8 surrounding tiles. Keep these effects small —
          something that touches everything nearby adds up fast.
        </p>
      )}
      {to.mode === 'all' && singleTarget && (
        <p className="text-[10px] text-gray-600 leading-relaxed">
          The output lands on this Token itself, like every other yield in the
          game. Pick a tag or a Token to send it to a neighbour instead.
        </p>
      )}
      {to.mode !== 'all' && singleTarget && (
        <p className="text-[10px] text-gray-600 leading-relaxed">
          Output goes to the <strong>nearest</strong> match — one destination,
          not all of them. A conversion spends a fixed input, so producing onto
          every neighbour would multiply the output and not the cost.
          {' '}If nothing nearby matches, the inputs are still spent and nothing
          is produced.
        </p>
      )}
    </div>
  );
}

/** The `When …` clause — offered only where the keyword allows one. */
function TriggerClause({ statement, tokens, items, onChange }) {
  const keyword = getKeyword(statement.keyword);
  const when = statement.when;
  const required = keyword.when === WHEN.REQUIRED;

  if (!when) {
    return (
      <button
        onClick={() => onChange({ when: { event: TRIGGER_EVENTS[0].id, scope: TRIGGER_EVENTS[0].scopes[0], cooldownMs: 5000 } })}
        className="flex items-center gap-1 px-2 py-1 rounded text-[10px]"
        style={{ background: 'rgba(255,255,255,0.04)', color: 'var(--color-text-secondary)', border: 'none', cursor: 'pointer' }}
      >
        <Plus size={10} /> Add a trigger
      </button>
    );
  }

  const definition = getTriggerEvent(when.event);
  const isGlobal = when.scope === 'global';
  // A self-scoped trigger has no neighbour to filter on and nothing outside
  // itself to watch — the Token that fires it is the Token that reacts.
  const isSelf = when.scope === 'self';
  const set = (changes) => onChange({ when: { ...when, ...changes } });

  return (
    <div className="rounded-md border border-white/5 bg-black/20 p-2.5 space-y-2">
      <label className="text-[10px] font-bold uppercase tracking-wider text-gray-500 flex items-center gap-1.5">
        <Zap size={11} /> When
        {!required && (
          <button
            onClick={() => onChange({ when: null })}
            className="ml-auto text-gray-600 hover:text-red-400 normal-case tracking-normal font-normal"
            style={{ background: 'none', border: 'none', cursor: 'pointer', fontSize: 10 }}
          >
            remove
          </button>
        )}
      </label>

      <select
        value={when.event}
        onChange={(e) => {
          const next = getTriggerEvent(e.target.value);
          set({ event: e.target.value, scope: next?.scopes[0] || 'adjacent' });
        }}
        className="w-full"
        style={{ fontSize: 12 }}
      >
        {TRIGGER_EVENTS.map((t) => (
          <option key={t.id} value={t.id}>{t.label}</option>
        ))}
      </select>
      {definition?.hint && <p className="text-[10px] text-gray-600 leading-relaxed">{definition.hint}</p>}

      {definition?.needsItem && (
        <ItemPicker
          label="Which item"
          value={when.watchItemId}
          items={items}
          onPick={(watchItemId) => set({ watchItemId })}
        />
      )}
      {definition?.needsItem && !when.watchItemId && (
        <p className="text-[10px]" style={{ color: 'var(--color-warning)' }}>
          ⚠️ With no item named this fires on nothing at all. Pick one, or use
          “a neighbour completes a cycle” instead.
        </p>
      )}

      {!isGlobal && !isSelf && (
        <div className="flex gap-3">
          <Field label="From which neighbour" className="flex-1">
            <select
              value={when.source?.mode || ''}
              onChange={(e) => set({ source: e.target.value ? { mode: e.target.value, value: '' } : null })}
              className="w-full"
              style={{ fontSize: 12 }}
            >
              <option value="">Any neighbour</option>
              {TARGET_MODES.filter((m) => m.mode !== 'all').map((m) => (
                <option key={m.mode} value={m.mode}>{m.label}</option>
              ))}
            </select>
          </Field>
          {when.source?.mode === 'id' && (
            <Field label="Token" className="flex-1">
              <select
                value={when.source.value || ''}
                onChange={(e) => set({ source: { mode: 'id', value: e.target.value } })}
                className="w-full"
                style={{ fontSize: 12 }}
              >
                <option value="">— pick a Token —</option>
                {Object.values(tokens).map((t) => <option key={t.id} value={t.id}>{t.name}</option>)}
              </select>
            </Field>
          )}
          {when.source?.mode === 'tag' && (
            <Field label="Tag" className="flex-1">
              <input
                type="text"
                value={when.source.value || ''}
                onChange={(e) => set({ source: { mode: 'tag', value: e.target.value } })}
                className="w-full"
                style={{ fontSize: 12 }}
              />
            </Field>
          )}
        </div>
      )}

      {isGlobal && (
        <div className="flex gap-3">
          <ItemPicker
            label="Watch for"
            value={when.watchItemId}
            items={items}
            onPick={(watchItemId) => set({ watchItemId })}
            className="flex-1"
          />
          <Field label="At least" className="w-24">
            <input
              type="number" min={1} value={when.threshold ?? 1}
              onChange={(e) => set({ threshold: Math.max(1, Number(e.target.value)) })}
              className="w-full" style={{ fontSize: 12 }}
            />
          </Field>
        </div>
      )}

      <Field label="At most once every (ms)">
        <input
          type="number" min={0} step={500} value={when.cooldownMs ?? 0}
          onChange={(e) => set({ cooldownMs: Math.max(0, Number(e.target.value)) })}
          className="w-full" style={{ fontSize: 11 }}
        />
      </Field>
      {isGlobal && !when.cooldownMs && (
        <p className="text-[10px]" style={{ color: 'var(--color-warning)' }}>
          ⚠️ With no cooldown, a condition that stays true fires on every change to the Bank.
        </p>
      )}
      {isSelf && (
        <p className="text-[10px] text-gray-600 leading-relaxed">
          This Token reacting to itself. Its rule still reaches outward from
          here as normal — the filter below decides who it lands on. A cooldown
          is a rate limit, not a safety net: the board stops a Token setting
          itself off in a circle on its own.
        </p>
      )}
    </div>
  );
}

/**
 * What this statement does to its Token's charges, and when (UE-20).
 *
 * ## ⚠️ Offered on every statement now, not just the ones that fire
 * It used to appear only on keywords that can carry a trigger, because firing
 * was the only moment anything spent at. The moment is authored now, so a
 * permanent aura can be made to cost its Token a charge each cycle — and the
 * always-on case, which is most of them, is simply a cost of `0`.
 *
 * ## The moment list comes from the game, not from here
 * `chargeMomentsFor` returns the moments that are legal for this statement, and
 * the game declares them. P5 and P6 each add one; this component does not change
 * when they do. A statement with no `When` clause is not offered "each time it
 * fires", because it never fires.
 *
 * ## The box is never blank
 * An absent `chargeDelta` is −1 on a firing rule and 0 on one that does not
 * fire, so the control shows the real effective number rather than an empty box
 * that means something. A free effect is a written `0`, which stays a different
 * thing from having written nothing.
 */
function ChargeClause({ statement, onChange }) {
  const moments = chargeMomentsFor(!!statement.when);
  const moment = chargeMomentOf(statement);
  const active = getChargeMoment(moment);
  const delta = typeof statement.chargeDelta === 'number'
    ? statement.chargeDelta
    : (DEFAULT_CHARGE_DELTA_BY_MOMENT[moment] ?? DEFAULT_STATEMENT_CHARGE_DELTA);

  const firing = moment === 'on_fire';

  return (
    <div className="rounded-md border border-white/5 bg-black/20 p-2.5 space-y-2">
      <label className="text-[10px] font-bold uppercase tracking-wider text-gray-500 flex items-center gap-1.5">
        <Zap size={11} /> Charge cost
      </label>

      <div className="flex gap-2">
        <input
          type="number"
          step={1}
          value={delta}
          onChange={(e) => onChange({ chargeDelta: Number(e.target.value), chargeWhen: moment })}
          className="w-20"
          style={{ fontSize: 11 }}
        />
        <select
          value={moment}
          onChange={(e) => onChange({ chargeWhen: e.target.value })}
          className="flex-1"
          style={{ fontSize: 11 }}
          disabled={moments.length < 2}
        >
          {moments.map((m) => (
            <option key={m.id} value={m.id}>{m.label}</option>
          ))}
        </select>
      </div>

      <p className="text-[10px] text-gray-600 leading-relaxed">
        {delta < 0
          ? firing
            ? `Spends ${-delta} charge${delta === -1 ? '' : 's'} each time it fires, and cannot fire at all with fewer left.`
            : `Spends ${-delta} charge${delta === -1 ? '' : 's'} every cycle this Token completes, on top of its own work cost.`
          : delta === 0
            ? 'Free — this rule never wears the Token down. This is how an always-on effect is authored.'
            : firing
              ? `Gives ${delta} charge${delta === 1 ? '' : 's'} back, up to the Token's starting charges.`
              : 'A per-cycle rule can only cost, never restore — a Token topping itself up every cycle would never deplete.'}
        {' '}A Token with unlimited charges ignores this in both directions.
      </p>

      {active?.hint && (
        <p className="text-[10px] text-gray-600 leading-relaxed italic">{active.hint}</p>
      )}
    </div>
  );
}

/** The `, costing …` clause. */
function UpkeepClause({ statement, items, onChange }) {
  const upkeep = statement.upkeep;

  if (!upkeep) {
    return (
      <button
        onClick={() => onChange({ upkeep: { items: [], cadenceMs: 30000 } })}
        className="flex items-center gap-1 px-2 py-1 rounded text-[10px]"
        style={{ background: 'rgba(255,255,255,0.04)', color: 'var(--color-text-secondary)', border: 'none', cursor: 'pointer' }}
      >
        <Plus size={10} /> Add an upkeep cost
      </button>
    );
  }

  const set = (changes) => onChange({ upkeep: { ...upkeep, ...changes } });

  return (
    <div className="rounded-md border border-white/5 bg-black/20 p-2.5 space-y-2">
      <label className="text-[10px] font-bold uppercase tracking-wider text-gray-500 flex items-center gap-1.5">
        <Coins size={11} /> Costing
        <button
          onClick={() => onChange({ upkeep: null })}
          className="ml-auto text-gray-600 hover:text-red-400 normal-case tracking-normal font-normal"
          style={{ background: 'none', border: 'none', cursor: 'pointer', fontSize: 10 }}
        >
          remove
        </button>
      </label>

      <ItemList
        label=""
        entries={upkeep.items || []}
        items={items}
        onChange={(next) => set({ items: next })}
      />

      <Field label="Every (ms)">
        <input
          type="number" min={1000} step={1000} value={upkeep.cadenceMs ?? 30000}
          onChange={(e) => set({ cadenceMs: Number(e.target.value) })}
          className="w-full" style={{ fontSize: 11 }}
        />
      </Field>
      <p className="text-[10px] text-gray-600 leading-relaxed">
        Its own clock, independent of any production cycle. When the Bank cannot
        pay, this rule switches off until stock returns — nothing is destroyed
        and no debt accrues.
      </p>
    </div>
  );
}

/**
 * **The** item picker.
 *
 * There were four hand-rolled copies of this in the old editor, each with the
 * same `toLowerCase().includes()` filter written out again, and the create-item
 * modal wired up twice. One control, used everywhere.
 */
function ItemPicker({ label, value, items, onPick, className }) {
  const [query, setQuery] = useState('');
  const [modalOpen, setModalOpen] = useState(false);

  const matches = query.trim()
    ? Object.values(items).filter((i) => (i.name || '').toLowerCase().includes(query.trim().toLowerCase())).slice(0, 5)
    : [];
  const exactExists = Object.values(items).some(
    (i) => (i.name || '').toLowerCase() === query.trim().toLowerCase()
  );

  return (
    <Field label={label} className={className}>
      {value ? (
        <div className="flex items-center gap-1.5">
          <span className="flex-1 truncate text-[11px] text-gray-300">{items[value]?.name || value}</span>
          <button
            onClick={() => onPick('')}
            className="text-gray-600 hover:text-red-400"
            style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 0, lineHeight: 0 }}
          >
            <X size={11} />
          </button>
        </div>
      ) : (
        <div className="relative">
          <Search size={11} className="absolute left-2 top-1/2 -translate-y-1/2 text-gray-600" />
          <input
            type="text"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Search items…"
            className="w-full pl-6"
            style={{ fontSize: 11 }}
          />
        </div>
      )}

      {!value && query.trim() && (
        <div className="mt-1 space-y-1">
          {matches.map((i) => (
            <button
              key={i.id}
              onClick={() => { onPick(i.id); setQuery(''); }}
              className="w-full text-left px-2 py-1 rounded text-[11px] text-gray-300 hover:bg-white/5"
              style={{ background: 'transparent', border: 'none', cursor: 'pointer' }}
            >
              {i.name}
            </button>
          ))}
          {!exactExists && (
            <button
              onClick={() => setModalOpen(true)}
              className="w-full flex items-center gap-1 px-2 py-1 rounded text-[11px] font-bold"
              style={{ background: 'var(--color-accent-muted)', color: 'var(--color-accent-hover)', border: 'none', cursor: 'pointer' }}
            >
              <Plus size={11} /> Create “{query.trim()}”
            </button>
          )}
        </div>
      )}

      <InlineItemModal
        isOpen={modalOpen}
        initialName={query.trim()}
        onClose={() => setModalOpen(false)}
        onCreated={(id) => { onPick(id); setQuery(''); }}
      />
    </Field>
  );
}

/** A list of `{itemId, quantity}` entries — upkeep, and both sides of Converts. */
function ItemList({ label, entries, items, onChange }) {
  return (
    <div>
      {label && (
        <label className="text-[10px] font-bold uppercase tracking-wider block mb-1.5 text-gray-500">{label}</label>
      )}
      <div className="space-y-1.5">
        {entries.map((entry, i) => (
          <div key={i} className="flex items-center gap-1.5">
            <span className="flex-1 text-[11px] text-gray-300 truncate">
              {items[entry.itemId]?.name || entry.itemId}
            </span>
            <input
              type="number" min={1} value={entry.quantity ?? 1}
              onChange={(e) => onChange(entries.map((x, idx) => (idx === i ? { ...x, quantity: Math.max(1, Number(e.target.value)) } : x)))}
              className="w-16" style={{ fontSize: 11, padding: '3px 6px' }}
            />
            <button
              onClick={() => onChange(entries.filter((_, idx) => idx !== i))}
              className="text-gray-600 hover:text-red-400"
              style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 0, lineHeight: 0 }}
            >
              <X size={11} />
            </button>
          </div>
        ))}
      </div>
      <ItemPicker
        label=""
        value=""
        items={items}
        onPick={(itemId) => itemId && onChange([...entries, { itemId, quantity: 1 }])}
      />
    </div>
  );
}

/**
 * Every capability tag the content actually uses — provided, or required.
 *
 * ⚠️ **Reads through the library** (Unified Effects P1). An `Acts as` rule lives
 * in a named entry now, not on the Token, so walking Tokens alone would return
 * an empty vocabulary and quietly turn every capability suggestion off.
 */
function useCapabilityVocabulary(tokens) {
  const effects = useEntityStore((s) => s.effects);
  return useMemo(() => {
    const tags = new Set();
    for (const t of Object.values(tokens)) {
      for (const p of providedTagsOf(expandBearer(t, effects || {}))) if (p.tag) tags.add(p.tag);
      for (const r of t.acceptedTokens || []) if (r?.tag) tags.add(r.tag);
    }
    return [...tags].sort();
  }, [tokens, effects]);
}

/**
 * A Token's provided capabilities, read the way the game reads them.
 *
 * ⚠️ The old editor typed its own list — `['pickaxe','axe','hammer','anvil',
 * 'saw','furnace','pie_tin','cookbook']` — straight into the component. That is
 * exactly the hand-maintained CMS vocabulary CMS-5 exists to forbid, and it had
 * already drifted from the content.
 */
function providedTagsOf(token) {
  const out = [];
  const defaultTier = token?.tier || 1;
  for (const s of statementsOf(token)) {
    if (s?.keyword === KEYWORD.ACTS_AS && s.payload?.tag) {
      out.push({ tag: s.payload.tag, tier: s.payload.tier || defaultTier });
    }
  }
  for (const p of token?.provides || []) {
    if (typeof p === 'string') out.push({ tag: p, tier: defaultTier });
    else if (p?.tag) out.push({ tag: p.tag, tier: p.tier || defaultTier });
  }
  return out;
}

function CapabilityDatalist({ capabilities }) {
  return (
    <datalist id="cms-capability-tags">
      {capabilities.map((c) => <option key={c} value={c} />)}
    </datalist>
  );
}
