import { useMemo, useState } from 'react';
import {
  Plus, X, Trash2, Search, ArrowUp, ArrowDown, Zap, Coins, Wrench, Package,
  Gauge, Truck, Repeat, HandCoins, Ban, Sparkles, Factory
} from 'lucide-react';
import { useEntityStore, makeModifier } from '../../stores/useEntityStore';
import {
  KEYWORD, KEYWORDS, WHEN, getKeyword, paletteForKeyword, makeStatement,
  renderStatement, statementsOf,
  MODIFIER_BUCKETS, TARGET_MODES, getPaletteEntry, MODIFIER_SHAPES,
  TRIGGER_EVENTS, getTriggerEvent, clampModifierValue, describeModifierDirection,
  RESTRICTION_KINDS, getRestrictionKind, blankRestriction, AUTHORABLE_STATUSES,
  SKILLS, DEFAULT_STATEMENT_CHARGE_DELTA,
} from '../../utils/constants';
import { Field } from '../shared/EditorLayout';
import InlineItemModal from '../shared/InlineItemModal';

/**
 * The Rules editor — a Token's statements, one sentence per row.
 *
 * ## What this replaced
 * `EffectBlocks.jsx`: 1,080 lines in which five unrelated mechanics — target,
 * capability provision, trigger, upkeep and a *list* of modifiers — shared one
 * container, all five visible on every block whether or not they applied. About
 * 490 of those lines were that crowding, and another 190 were four separate
 * hand-rolled item pickers.
 *
 * Here a row shows only what its keyword needs, and there is one item picker.
 *
 * ## The row IS the sentence
 * Every row ends with its own rules text, generated by the same function the
 * game's tooltip uses. That is the validation: if the sentence says something
 * you did not mean, the rule says something you did not mean. A flipped sign
 * reads "5% **more** work time"; a tag typo reads "adjacent **Coste** Tokens".
 *
 * ## ⚠️ Requires is a view of `acceptedTokens`, not a statement
 * Owner decision Q5. That field gates whether a station produces anything at
 * all — `RecipeResolver.checkAcceptedTokens` is the highest-consequence reader
 * in the system — so it stays exactly where it is and only its presentation
 * moves into this list. The author sees one unified set of sentences; the
 * engine sees no change whatsoever.
 */

const KEYWORD_ICON = {
  [KEYWORD.PROVIDES]: Gauge,
  [KEYWORD.GRANTS]: HandCoins,
  [KEYWORD.ACTS_AS]: Wrench,
  [KEYWORD.REQUIRES]: Package,
  [KEYWORD.RESTOCKS]: Truck,
  [KEYWORD.CONVERTS]: Repeat,
  [KEYWORD.CANNOT]: Ban,
  [KEYWORD.APPLIES]: Sparkles,
  [KEYWORD.STATION]: Factory,
};

export default function Statements({ token }) {
  const setStatements = useEntityStore((s) => s.setStatements);
  const updateToken = useEntityStore((s) => s.updateToken);
  const tokens = useEntityStore((s) => s.tokens);
  const items = useEntityStore((s) => s.items);
  const [menuOpen, setMenuOpen] = useState(false);

  const statements = statementsOf(token);
  const requirements = token.acceptedTokens || [];

  const write = (next) => setStatements(token.id, next);
  const patch = (id, changes) =>
    write(statements.map((s) => (s.id === id ? { ...s, ...changes } : s)));
  const remove = (id) => write(statements.filter((s) => s.id !== id));
  const move = (id, by) => {
    const from = statements.findIndex((s) => s.id === id);
    const to = from + by;
    if (from < 0 || to < 0 || to >= statements.length) return;
    const next = [...statements];
    const [row] = next.splice(from, 1);
    next.splice(to, 0, row);
    write(next);
  };

  const setRequirements = (next) => updateToken(token.id, { acceptedTokens: next });

  const add = (keywordId) => {
    setMenuOpen(false);
    if (keywordId === KEYWORD.REQUIRES) {
      setRequirements([...requirements, { tag: '', minTier: 1 }]);
      return;
    }
    write([...statements, makeStatement(keywordId)]);
  };

  const names = useMemo(() => ({
    token: (id) => tokens[id]?.name || id,
    item: (id) => items[id]?.name || id,
  }), [tokens, items]);

  const isEmpty = statements.length === 0 && requirements.length === 0;

  return (
    <div className="space-y-3">
      {isEmpty && (
        <p className="text-[11px] text-gray-500 leading-relaxed">
          No rules. A pure producer needs none — rules are for Tokens that change
          what happens <em>around</em> them, hand a capability to a neighbour, or
          need one themselves.
        </p>
      )}

      {token.effectBlocks?.length > 0 && (
        <div
          className="rounded-lg p-3 text-[11px] leading-relaxed"
          style={{ background: 'rgba(255,180,0,0.08)', border: '1px solid rgba(255,180,0,0.3)', color: 'var(--color-warning)' }}
        >
          ⚠️ This Token still carries <strong>effect blocks</strong> from the old
          editor. They are not read by the game any more, so it currently does
          nothing. Rebuild its rules below — adding the first rule clears the old
          data for good.
        </div>
      )}

      {requirements.map((req, i) => (
        <RequiresRow
          key={`req_${i}`}
          requirement={req}
          tokens={tokens}
          names={names}
          onChange={(next) => setRequirements(requirements.map((r, idx) => (idx === i ? next : r)))}
          onRemove={() => setRequirements(requirements.filter((_, idx) => idx !== i))}
        />
      ))}

      {statements.map((statement, i) => (
        <StatementRow
          key={statement.id}
          statement={statement}
          token={token}
          tokens={tokens}
          items={items}
          names={names}
          canMoveUp={i > 0}
          canMoveDown={i < statements.length - 1}
          onMove={(by) => move(statement.id, by)}
          onChange={(changes) => patch(statement.id, changes)}
          onRemove={() => remove(statement.id)}
        />
      ))}

      <div className="pt-1">
        {menuOpen ? (
          <div className="rounded-lg border border-white/10 bg-black/30 p-2 space-y-1">
            {KEYWORDS.map((k) => {
              const Icon = KEYWORD_ICON[k.id] || Zap;
              return (
                <button
                  key={k.id}
                  onClick={() => add(k.id)}
                  className="w-full text-left flex items-start gap-2 px-2 py-1.5 rounded hover:bg-white/5"
                  style={{ background: 'transparent', border: 'none', cursor: 'pointer' }}
                >
                  <Icon size={13} className="text-emerald-400 mt-0.5 flex-shrink-0" />
                  <span className="flex-1">
                    <span className="block text-xs text-gray-200 font-medium">{k.label}</span>
                    <span className="block text-[10px] text-gray-500 leading-snug">{k.blurb}</span>
                  </span>
                </button>
              );
            })}
            <button
              onClick={() => setMenuOpen(false)}
              className="w-full text-center text-[10px] text-gray-500 py-1"
              style={{ background: 'transparent', border: 'none', cursor: 'pointer' }}
            >
              cancel
            </button>
          </div>
        ) : (
          <button
            onClick={() => setMenuOpen(true)}
            className="flex items-center gap-1 px-2.5 py-1.5 rounded text-[11px]"
            style={{ background: 'var(--color-accent-muted)', color: 'var(--color-accent-hover)', border: 'none', cursor: 'pointer' }}
          >
            <Plus size={12} /> Add rule
          </button>
        )}
      </div>
    </div>
  );
}

/** One row's chrome: keyword name, reorder, delete, and the sentence. */
function RowShell({ keywordId, sentence, onMove, canMoveUp, canMoveDown, onRemove, children }) {
  const keyword = getKeyword(keywordId);
  const Icon = KEYWORD_ICON[keywordId] || Zap;
  return (
    <div className="rounded-lg border border-white/10 bg-black/20">
      <div className="flex items-center gap-2 px-3 py-2 border-b border-white/5">
        <Icon size={13} className="text-emerald-400" />
        <span className="text-xs font-medium text-gray-200">{keyword?.label || keywordId}</span>
        <span className="flex-1" />
        {onMove && (
          <>
            <button
              onClick={() => onMove(-1)}
              disabled={!canMoveUp}
              className="text-gray-600 hover:text-gray-300 disabled:opacity-20"
              style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 0, lineHeight: 0 }}
              title="Move up"
            >
              <ArrowUp size={12} />
            </button>
            <button
              onClick={() => onMove(1)}
              disabled={!canMoveDown}
              className="text-gray-600 hover:text-gray-300 disabled:opacity-20"
              style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 0, lineHeight: 0 }}
              title="Move down"
            >
              <ArrowDown size={12} />
            </button>
          </>
        )}
        <button
          onClick={onRemove}
          className="text-gray-600 hover:text-red-400"
          style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 0, lineHeight: 0 }}
          title="Remove rule"
        >
          <Trash2 size={12} />
        </button>
      </div>

      <div className="p-3 space-y-2.5">{children}</div>

      <p className="px-3 py-2 border-t border-white/5 text-[11px] italic text-emerald-300/90 leading-relaxed">
        “{sentence}”
      </p>
    </div>
  );
}

/** Requires — a view of the top-level `acceptedTokens` field (owner Q5). */
function RequiresRow({ requirement, tokens, names, onChange, onRemove }) {
  const capabilities = useCapabilityVocabulary(tokens);
  const sentence = renderStatement(
    { keyword: KEYWORD.REQUIRES, payload: requirement }, names
  );
  const providers = Object.values(tokens).filter((t) =>
    providedTagsOf(t).some((p) => p.tag === requirement.tag && (p.tier || 1) >= (requirement.minTier || 1))
  );

  return (
    <RowShell keywordId={KEYWORD.REQUIRES} sentence={sentence} onRemove={onRemove}>
      <div className="flex gap-3">
        <Field label="Capability" className="flex-1">
          <input
            type="text"
            list="cms-capability-tags"
            value={requirement.tag || ''}
            placeholder="e.g. pickaxe"
            onChange={(e) => onChange({ ...requirement, tag: e.target.value.trim().toLowerCase() })}
            className="w-full"
            style={{ fontSize: 12 }}
          />
        </Field>
        <Field label="Min Tool Tier" className="w-28">
          <input
            type="number"
            min={1}
            value={requirement.minTier ?? 1}
            onChange={(e) => onChange({ ...requirement, minTier: Math.max(1, Number(e.target.value)) })}
            className="w-full"
            style={{ fontSize: 12 }}
          />
        </Field>
      </div>
      <CapabilityDatalist capabilities={capabilities} />
      <p className="text-[10px] text-gray-500">
        Satisfied by:{' '}
        {providers.length === 0 ? (
          <span className="text-amber-400">nothing yet — this Token can never work</span>
        ) : (
          providers.map((t) => t.name).join(', ')
        )}
      </p>
    </RowShell>
  );
}

/** One real statement. */
function StatementRow({ statement, tokens, items, names, onChange, onRemove, onMove, canMoveUp, canMoveDown }) {
  const keyword = getKeyword(statement.keyword);
  const sentence = renderStatement(statement, names);

  return (
    <RowShell
      keywordId={statement.keyword}
      sentence={sentence}
      onRemove={onRemove}
      onMove={onMove}
      canMoveUp={canMoveUp}
      canMoveDown={canMoveDown}
    >
      <PayloadFields statement={statement} tokens={tokens} items={items} onChange={onChange} />

      {keyword?.filter && (
        <FilterPicker
          statement={statement}
          tokens={tokens}
          onChange={onChange}
          // The same filter, asked three different ways round. "Reaches" is
          // wrong in front of a restriction and wrong in front of a status, and
          // a label that reads wrong is how an author picks the wrong thing.
          label={
            statement.keyword === KEYWORD.CANNOT ? 'Too many of what'
              : statement.keyword === KEYWORD.APPLIES ? 'Heroes working'
                : 'Reaches'
          }
        />
      )}

      {keyword?.when !== WHEN.NEVER && (
        <>
          <TriggerClause statement={statement} tokens={tokens} items={items} onChange={onChange} />
          <ChargeClause statement={statement} onChange={onChange} />
        </>
      )}

      {keyword?.upkeep && <UpkeepClause statement={statement} items={items} onChange={onChange} />}
    </RowShell>
  );
}

/** The payload — different for every keyword, and only ever one thing. */
function PayloadFields({ statement, tokens, items, onChange }) {
  const payload = statement.payload || {};
  const setPayload = (changes) => onChange({ payload: { ...payload, ...changes } });

  switch (statement.keyword) {
    case KEYWORD.PROVIDES:
      return <EffectFields statement={statement} onChange={onChange} />;

    case KEYWORD.GRANTS:
      return (
        <div className="flex gap-3 items-end">
          <ItemPicker
            label="Item"
            value={payload.itemId}
            items={items}
            onPick={(itemId) => setPayload({ itemId })}
            className="flex-1"
          />
          <Field label="How many" className="w-24">
            <input
              type="number" min={1} value={payload.quantity ?? 1}
              onChange={(e) => setPayload({ quantity: Math.max(1, Number(e.target.value)) })}
              className="w-full" style={{ fontSize: 12 }}
            />
          </Field>
          <Field label="Chance %" className="w-24">
            <input
              type="number" min={1} max={100} value={payload.chance ?? 100}
              onChange={(e) => setPayload({ chance: Math.min(100, Math.max(1, Number(e.target.value))) })}
              className="w-full" style={{ fontSize: 12 }}
            />
          </Field>
        </div>
      );

    case KEYWORD.STATION:
      return <StationFields payload={payload} setPayload={setPayload} />;

    case KEYWORD.ACTS_AS:
      return <ActsAsFields payload={payload} tokens={tokens} setPayload={setPayload} />;

    case KEYWORD.RESTOCKS:
      return <RestocksFields payload={payload} tokens={tokens} setPayload={setPayload} />;

    case KEYWORD.CANNOT:
      return <CannotFields payload={payload} setPayload={setPayload} onChange={onChange} />;

    case KEYWORD.APPLIES:
      return <AppliesFields payload={payload} setPayload={setPayload} />;

    case KEYWORD.CONVERTS:
      return (
        <div className="grid grid-cols-2 gap-3">
          <ItemList
            label="Spends from the Bank"
            entries={payload.consumes || []}
            items={items}
            onChange={(consumes) => setPayload({ consumes })}
          />
          <ItemList
            label="Produces on the board"
            entries={payload.produces || []}
            items={items}
            onChange={(produces) => setPayload({ produces })}
          />
        </div>
      );

    default:
      return null;
  }
}

/**
 * The one field a Station statement has: which skill's recipes it can run.
 *
 * The list comes from the game's `skillRegistry` (via `constants.js`), so the
 * CMS can never offer a skill the game has not heard of — the drift CMS-5
 * exists to prevent, and the exact failure that produced `industry` and
 * `culinary` in the old content.
 */
function StationFields({ payload, setPayload }) {
  return (
    <div className="flex gap-3">
      <Field label="Skill" className="w-56">
        <select
          value={payload.skill || ''}
          onChange={(e) => setPayload({ skill: e.target.value })}
          className="w-full"
          style={{ fontSize: 12 }}
        >
          <option value="">Pick a skill…</option>
          {SKILLS.map((s) => (
            <option key={s.id} value={s.id}>{s.name}</option>
          ))}
        </select>
      </Field>
    </div>
  );
}

/**
 * The number effect, with the **direction trap** designed out.
 *
 * ⚠️ You used to type `-0.05` into a box labelled "Value (−0.05 = 5% less)" on
 * an axis where lower is better, and nothing stopped you typing `0.05` and
 * shipping a curse — which is exactly what happened to the Forge Altar. Here
 * the magnitude is always positive and the **direction is a word**; the palette
 * already knows which axes run backwards (`inverted`), so the sign is derived
 * and the sentence reads back in the words you chose.
 */
function EffectFields({ statement, onChange }) {
  const payload = statement.payload || {};
  const entry = getPaletteEntry(payload.type);
  const palette = paletteForKeyword(KEYWORD.PROVIDES, !!statement.when);
  const isProc = entry?.shape === MODIFIER_SHAPES.PROC;
  const bucket = payload.bucket || 'percentage';
  const direction = describeModifierDirection(entry, payload.value, bucket);

  const magnitude = () => {
    const v = Math.abs(Number(payload.value) || 0);
    return bucket === 'percentage' && !isProc ? Math.round(v * 1000) / 10 : v;
  };

  const writeMagnitude = (raw, sign) => {
    const n = Math.abs(Number(raw) || 0);
    const scaled = bucket === 'percentage' && !isProc ? n / 100 : n;
    onChange({ payload: { ...payload, value: clampModifierValue(entry, scaled * sign) } });
  };

  const sign = Number(payload.value) < 0 ? -1 : 1;

  return (
    <div className="space-y-2">
      <div className="flex gap-3 items-end">
        <Field label="Effect" className="flex-1">
          <select
            value={payload.type || ''}
            onChange={(e) => {
              const next = getPaletteEntry(e.target.value);
              onChange({ payload: makeModifier(e.target.value, next?.shape) });
            }}
            className="w-full"
            style={{ fontSize: 12 }}
          >
            {palette.map((p) => (
              <option key={p.type} value={p.type}>{p.label}</option>
            ))}
          </select>
        </Field>

        {!isProc && (
          <Field label="How it combines" className="w-32">
            <select
              value={bucket}
              onChange={(e) => onChange({ payload: { ...payload, bucket: e.target.value } })}
              className="w-full"
              style={{ fontSize: 12 }}
            >
              {MODIFIER_BUCKETS.map((b) => (
                <option key={b} value={b}>
                  {b === 'percentage' ? '5%' : b === 'flat' ? '+5' : '×1.5'}
                </option>
              ))}
            </select>
          </Field>
        )}

        <Field label={isProc ? 'Chance %' : 'Amount'} className="w-24">
          <input
            type="number"
            min={0}
            step={bucket === 'multiplier' ? 0.1 : 1}
            value={magnitude()}
            onChange={(e) => writeMagnitude(e.target.value, sign)}
            className="w-full"
            style={{ fontSize: 12 }}
          />
        </Field>

        {!isProc && bucket !== 'multiplier' && (
          <Field label="Direction" className="w-40">
            <select
              value={sign < 0 ? 'less' : 'more'}
              onChange={(e) => writeMagnitude(magnitude(), e.target.value === 'less' ? -1 : 1)}
              className="w-full"
              style={{ fontSize: 12 }}
            >
              <option value="more">more {entry?.inverted ? '(a penalty)' : '(a buff)'}</option>
              <option value="less">less {entry?.inverted ? '(a buff)' : '(a penalty)'}</option>
            </select>
          </Field>
        )}
      </div>

      {entry?.hint && <p className="text-[10px] text-gray-600 leading-relaxed">{entry.hint}</p>}
      {direction && (
        <p className="text-[10px]" style={{ color: direction.isBuff ? 'var(--color-accent-hover)' : 'var(--color-warning)' }}>
          {direction.text}
        </p>
      )}
    </div>
  );
}

/** Acts as — capability plus **Tool Tier**, which lives on the sentence. */
function ActsAsFields({ payload, tokens, setPayload }) {
  const capabilities = useCapabilityVocabulary(tokens);
  return (
    <div className="space-y-2">
      <div className="flex gap-3">
        <Field label="Capability" className="flex-1">
          <input
            type="text"
            list="cms-capability-tags"
            value={payload.tag || ''}
            placeholder="e.g. pickaxe"
            onChange={(e) => setPayload({ tag: e.target.value.trim().toLowerCase() })}
            className="w-full"
            style={{ fontSize: 12 }}
          />
        </Field>
        <Field label="Tool Tier" className="w-28">
          <input
            type="number" min={1} value={payload.tier ?? 1}
            onChange={(e) => setPayload({ tier: Math.max(1, Number(e.target.value)) })}
            className="w-full" style={{ fontSize: 12 }}
          />
        </Field>
      </div>
      <CapabilityDatalist capabilities={capabilities} />
      <p className="text-[10px] text-gray-600 leading-relaxed">
        A station asking for a Tier 2 tool will not accept a Tier 1 one. This is
        the other end of the same wire as a rule’s <strong>Min Tool Tier</strong>.
      </p>
    </div>
  );
}

/** Restocks — the list of Token types this Manager keeps supplied. */
function RestocksFields({ payload, tokens, setPayload }) {
  const chosen = payload.tokenIds || [];
  return (
    <div className="space-y-2">
      <div className="flex flex-wrap gap-1.5">
        {chosen.length === 0 && <span className="text-[11px] text-gray-600">Nothing yet.</span>}
        {chosen.map((id) => (
          <span key={id} className="inline-flex items-center gap-1 px-2 py-1 rounded-md text-[11px] bg-white/5 border border-white/10 text-gray-300">
            {tokens[id]?.name || id}
            <button
              onClick={() => setPayload({ tokenIds: chosen.filter((x) => x !== id) })}
              className="text-gray-500 hover:text-red-400"
              style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 0, lineHeight: 0 }}
            >
              <X size={10} />
            </button>
          </span>
        ))}
      </div>
      <select
        value=""
        onChange={(e) => e.target.value && setPayload({ tokenIds: [...new Set([...chosen, e.target.value])] })}
        className="w-full"
        style={{ fontSize: 12 }}
      >
        <option value="">— add a Token to restock —</option>
        {Object.values(tokens).map((t) => (
          <option key={t.id} value={t.id}>{t.name}</option>
        ))}
      </select>
      <p className="text-[10px] text-gray-600 leading-relaxed">
        Covers the 8 surrounding tiles and never wears out, but it can only move
        a Token from the Bank — an empty Bank simply means the tile stays bare.
      </p>
    </div>
  );
}

/**
 * Cannot — a restriction kind and its limit.
 *
 * The kind list has exactly one row today (design §1.3). It is still a picker
 * rather than a hardcoded "more than N" form, because that is the difference
 * between adding restriction #2 as a row in a registry and adding it as a
 * rewrite of this component.
 */
function CannotFields({ payload, setPayload, onChange }) {
  const kind = getRestrictionKind(payload.kind);

  return (
    <div className="space-y-2">
      <div className="flex gap-3">
        <Field label="Cannot" className="flex-1">
          <select
            value={payload.kind || ''}
            onChange={(e) => onChange({ payload: blankRestriction(e.target.value) })}
            className="w-full"
            style={{ fontSize: 12 }}
          >
            {RESTRICTION_KINDS.map((k) => (
              <option key={k.id} value={k.id}>{k.label}</option>
            ))}
          </select>
        </Field>
        {payload.kind === 'adjacency_limit' && (
          <Field label="No more than" className="w-28">
            <input
              type="number" min={0} value={payload.max ?? 2}
              onChange={(e) => setPayload({ max: Math.max(0, Number(e.target.value)) })}
              className="w-full" style={{ fontSize: 12 }}
            />
          </Field>
        )}
      </div>
      {kind?.blurb && <p className="text-[10px] text-gray-600 leading-relaxed">{kind.blurb}</p>}
      <p className="text-[10px] text-gray-600 leading-relaxed">
        Breaking this refuses the drop: the Token flies back to wherever it came
        from and the board flashes the reason. Nothing is ever destroyed, and a
        saved board that already breaks the rule sends the offender to the Vault.
      </p>
    </div>
  );
}

/**
 * Applies — a status, and how many stacks of it.
 *
 * ⚠️ **The filter below selects Tokens; the status lands on a person.** The
 * owner ruled that this uses the same filter as every other keyword, so there
 * is one targeting concept in the grammar rather than two — which means the
 * honest reading of "adjacent Coast Tokens" here is *the heroes working them*.
 * The generated sentence says exactly that, in those words.
 */
function AppliesFields({ payload, setPayload }) {
  const status = AUTHORABLE_STATUSES.find((s) => s.id === payload.statusId);

  return (
    <div className="space-y-2">
      <div className="flex gap-3 items-end">
        <Field label="Status" className="flex-1">
          <select
            value={payload.statusId || ''}
            onChange={(e) => setPayload({ statusId: e.target.value })}
            className="w-full"
            style={{ fontSize: 12 }}
          >
            <option value="">— pick a status —</option>
            {AUTHORABLE_STATUSES.map((s) => (
              <option key={s.id} value={s.id}>{s.icon} {s.name}</option>
            ))}
          </select>
        </Field>
        <Field label="Stacks" className="w-24">
          <input
            type="number" min={1} value={payload.stacks ?? 1}
            onChange={(e) => setPayload({ stacks: Math.max(1, Number(e.target.value)) })}
            className="w-full" style={{ fontSize: 12 }}
          />
        </Field>
        <Field label="Chance %" className="w-24">
          <input
            type="number" min={1} max={100} value={payload.chance ?? 100}
            onChange={(e) => setPayload({ chance: Math.min(100, Math.max(1, Number(e.target.value))) })}
            className="w-full" style={{ fontSize: 12 }}
          />
        </Field>
      </div>

      {status && (
        <p
          className="text-[10px] leading-relaxed"
          style={{ color: status.category === 'debuff' ? 'var(--color-warning)' : 'var(--color-accent-hover)' }}
        >
          {status.description}
        </p>
      )}
      {status?.combatOnly && (
        <p className="text-[10px]" style={{ color: 'var(--color-warning)' }}>
          ⚠️ {status.name} clears the moment a fight ends, so it does nothing at
          all on a hero who is working rather than fighting.
        </p>
      )}
    </div>
  );
}

/** Which neighbours the statement reaches. */
function FilterPicker({ statement, tokens, onChange, label = 'Reaches' }) {
  const to = statement.to || { mode: 'all', value: '' };
  const knownTags = useMemo(() => {
    const all = new Set();
    for (const t of Object.values(tokens)) for (const tag of t.tags || []) all.add(tag);
    return [...all].sort();
  }, [tokens]);

  const tagMisses = to.mode === 'tag' && to.value && !knownTags.includes(to.value);
  const nearMiss = tagMisses && knownTags.find((t) => t.toLowerCase() === to.value.toLowerCase());

  return (
    <div className="space-y-1.5">
      <div className="flex gap-3">
        <Field label={label} className="flex-1">
          <select
            value={to.mode}
            onChange={(e) => onChange({ to: { mode: e.target.value, value: '' } })}
            className="w-full"
            style={{ fontSize: 12 }}
          >
            {TARGET_MODES.map((m) => (
              <option key={m.mode} value={m.mode}>{m.label}</option>
            ))}
          </select>
        </Field>

        {to.mode === 'tag' && (
          <Field label="Tag" className="flex-1">
            <input
              type="text"
              list="cms-known-token-tags"
              value={to.value || ''}
              onChange={(e) => onChange({ to: { mode: 'tag', value: e.target.value } })}
              placeholder="e.g. Coast"
              className="w-full"
              style={{ fontSize: 12 }}
            />
            <datalist id="cms-known-token-tags">
              {knownTags.map((t) => <option key={t} value={t} />)}
            </datalist>
          </Field>
        )}

        {to.mode === 'id' && (
          <Field label="Token" className="flex-1">
            <select
              value={to.value || ''}
              onChange={(e) => onChange({ to: { mode: 'id', value: e.target.value } })}
              className="w-full"
              style={{ fontSize: 12 }}
            >
              <option value="">— pick a Token —</option>
              {Object.values(tokens).map((t) => (
                <option key={t.id} value={t.id}>{t.name}</option>
              ))}
            </select>
          </Field>
        )}
      </div>

      {tagMisses && (
        <p className="text-[10px]" style={{ color: 'var(--color-warning)' }}>
          ⚠️ No Token carries the tag “{to.value}”, so this reaches nothing.
          {nearMiss && <> Did you mean <strong>{nearMiss}</strong>? Tags match exactly, including case.</>}
        </p>
      )}
      {to.mode === 'all' && (
        <p className="text-[10px] text-gray-600 leading-relaxed">
          Every Token on the 8 surrounding tiles. Keep these effects small —
          something that touches everything nearby adds up fast.
        </p>
      )}
    </div>
  );
}

/** The `When …` clause — offered only where the keyword allows one. */
function TriggerClause({ statement, tokens, items, onChange }) {
  const keyword = getKeyword(statement.keyword);
  const when = statement.when;
  const required = keyword.when === WHEN.REQUIRED;

  if (!when) {
    return (
      <button
        onClick={() => onChange({ when: { event: TRIGGER_EVENTS[0].id, scope: TRIGGER_EVENTS[0].scopes[0], cooldownMs: 5000 } })}
        className="flex items-center gap-1 px-2 py-1 rounded text-[10px]"
        style={{ background: 'rgba(255,255,255,0.04)', color: 'var(--color-text-secondary)', border: 'none', cursor: 'pointer' }}
      >
        <Plus size={10} /> Add a trigger
      </button>
    );
  }

  const definition = getTriggerEvent(when.event);
  const isGlobal = when.scope === 'global';
  // A self-scoped trigger has no neighbour to filter on and nothing outside
  // itself to watch — the Token that fires it is the Token that reacts.
  const isSelf = when.scope === 'self';
  const set = (changes) => onChange({ when: { ...when, ...changes } });

  return (
    <div className="rounded-md border border-white/5 bg-black/20 p-2.5 space-y-2">
      <label className="text-[10px] font-bold uppercase tracking-wider text-gray-500 flex items-center gap-1.5">
        <Zap size={11} /> When
        {!required && (
          <button
            onClick={() => onChange({ when: null })}
            className="ml-auto text-gray-600 hover:text-red-400 normal-case tracking-normal font-normal"
            style={{ background: 'none', border: 'none', cursor: 'pointer', fontSize: 10 }}
          >
            remove
          </button>
        )}
      </label>

      <select
        value={when.event}
        onChange={(e) => {
          const next = getTriggerEvent(e.target.value);
          set({ event: e.target.value, scope: next?.scopes[0] || 'adjacent' });
        }}
        className="w-full"
        style={{ fontSize: 12 }}
      >
        {TRIGGER_EVENTS.map((t) => (
          <option key={t.id} value={t.id}>{t.label}</option>
        ))}
      </select>
      {definition?.hint && <p className="text-[10px] text-gray-600 leading-relaxed">{definition.hint}</p>}

      {definition?.needsItem && (
        <ItemPicker
          label="Which item"
          value={when.watchItemId}
          items={items}
          onPick={(watchItemId) => set({ watchItemId })}
        />
      )}
      {definition?.needsItem && !when.watchItemId && (
        <p className="text-[10px]" style={{ color: 'var(--color-warning)' }}>
          ⚠️ With no item named this fires on nothing at all. Pick one, or use
          “a neighbour completes a cycle” instead.
        </p>
      )}

      {!isGlobal && !isSelf && (
        <div className="flex gap-3">
          <Field label="From which neighbour" className="flex-1">
            <select
              value={when.source?.mode || ''}
              onChange={(e) => set({ source: e.target.value ? { mode: e.target.value, value: '' } : null })}
              className="w-full"
              style={{ fontSize: 12 }}
            >
              <option value="">Any neighbour</option>
              {TARGET_MODES.filter((m) => m.mode !== 'all').map((m) => (
                <option key={m.mode} value={m.mode}>{m.label}</option>
              ))}
            </select>
          </Field>
          {when.source?.mode === 'id' && (
            <Field label="Token" className="flex-1">
              <select
                value={when.source.value || ''}
                onChange={(e) => set({ source: { mode: 'id', value: e.target.value } })}
                className="w-full"
                style={{ fontSize: 12 }}
              >
                <option value="">— pick a Token —</option>
                {Object.values(tokens).map((t) => <option key={t.id} value={t.id}>{t.name}</option>)}
              </select>
            </Field>
          )}
          {when.source?.mode === 'tag' && (
            <Field label="Tag" className="flex-1">
              <input
                type="text"
                value={when.source.value || ''}
                onChange={(e) => set({ source: { mode: 'tag', value: e.target.value } })}
                className="w-full"
                style={{ fontSize: 12 }}
              />
            </Field>
          )}
        </div>
      )}

      {isGlobal && (
        <div className="flex gap-3">
          <ItemPicker
            label="Watch for"
            value={when.watchItemId}
            items={items}
            onPick={(watchItemId) => set({ watchItemId })}
            className="flex-1"
          />
          <Field label="At least" className="w-24">
            <input
              type="number" min={1} value={when.threshold ?? 1}
              onChange={(e) => set({ threshold: Math.max(1, Number(e.target.value)) })}
              className="w-full" style={{ fontSize: 12 }}
            />
          </Field>
        </div>
      )}

      <Field label="At most once every (ms)">
        <input
          type="number" min={0} step={500} value={when.cooldownMs ?? 0}
          onChange={(e) => set({ cooldownMs: Math.max(0, Number(e.target.value)) })}
          className="w-full" style={{ fontSize: 11 }}
        />
      </Field>
      {isGlobal && !when.cooldownMs && (
        <p className="text-[10px]" style={{ color: 'var(--color-warning)' }}>
          ⚠️ With no cooldown, a condition that stays true fires on every change to the Bank.
        </p>
      )}
      {isSelf && (
        <p className="text-[10px] text-gray-600 leading-relaxed">
          This Token reacting to itself. Its rule still reaches outward from
          here as normal — the filter below decides who it lands on. A cooldown
          is a rate limit, not a safety net: the board stops a Token setting
          itself off in a circle on its own.
        </p>
      )}
    </div>
  );
}

/**
 * What one firing of this statement does to the Token's charges (concept §3.2).
 *
 * Offered on the keywords that can carry a trigger, because
 * `TriggerSystem.fireStatement` is the only reader and it only ever sees
 * statements with a `When` clause.
 *
 * ⚠️ **The box is never blank.** `Charges.statementChargeDelta` treats an absent
 * field as -1, not 0 — every statement authored before the field existed spent
 * one charge per firing and still does. So the control shows that -1 as a real
 * number and writes whatever the author leaves it at; a free effect is a written
 * `0`, which is a different thing from having written nothing.
 */
function ChargeClause({ statement, onChange }) {
  const delta = typeof statement.chargeDelta === 'number'
    ? statement.chargeDelta
    : DEFAULT_STATEMENT_CHARGE_DELTA;

  return (
    <div className="rounded-md border border-white/5 bg-black/20 p-2.5 space-y-2">
      <label className="text-[10px] font-bold uppercase tracking-wider text-gray-500 flex items-center gap-1.5">
        <Zap size={11} /> Charges per firing
      </label>
      <input
        type="number"
        step={1}
        value={delta}
        onChange={(e) => onChange({ chargeDelta: Number(e.target.value) })}
        className="w-full"
        style={{ fontSize: 11 }}
      />
      <p className="text-[10px] text-gray-600 leading-relaxed">
        {delta < 0
          ? `Spends ${-delta} charge${delta === -1 ? '' : 's'} each time it fires, and cannot fire at all with fewer left.`
          : delta === 0
            ? 'Free — this rule never wears the Token down.'
            : `Gives ${delta} charge${delta === 1 ? '' : 's'} back, up to the Token's starting charges.`}
        {' '}A Token with unlimited charges ignores this in both directions.
      </p>
    </div>
  );
}

/** The `, costing …` clause. */
function UpkeepClause({ statement, items, onChange }) {
  const upkeep = statement.upkeep;

  if (!upkeep) {
    return (
      <button
        onClick={() => onChange({ upkeep: { items: [], cadenceMs: 30000 } })}
        className="flex items-center gap-1 px-2 py-1 rounded text-[10px]"
        style={{ background: 'rgba(255,255,255,0.04)', color: 'var(--color-text-secondary)', border: 'none', cursor: 'pointer' }}
      >
        <Plus size={10} /> Add an upkeep cost
      </button>
    );
  }

  const set = (changes) => onChange({ upkeep: { ...upkeep, ...changes } });

  return (
    <div className="rounded-md border border-white/5 bg-black/20 p-2.5 space-y-2">
      <label className="text-[10px] font-bold uppercase tracking-wider text-gray-500 flex items-center gap-1.5">
        <Coins size={11} /> Costing
        <button
          onClick={() => onChange({ upkeep: null })}
          className="ml-auto text-gray-600 hover:text-red-400 normal-case tracking-normal font-normal"
          style={{ background: 'none', border: 'none', cursor: 'pointer', fontSize: 10 }}
        >
          remove
        </button>
      </label>

      <ItemList
        label=""
        entries={upkeep.items || []}
        items={items}
        onChange={(next) => set({ items: next })}
      />

      <Field label="Every (ms)">
        <input
          type="number" min={1000} step={1000} value={upkeep.cadenceMs ?? 30000}
          onChange={(e) => set({ cadenceMs: Number(e.target.value) })}
          className="w-full" style={{ fontSize: 11 }}
        />
      </Field>
      <p className="text-[10px] text-gray-600 leading-relaxed">
        Its own clock, independent of any production cycle. When the Bank cannot
        pay, this rule switches off until stock returns — nothing is destroyed
        and no debt accrues.
      </p>
    </div>
  );
}

/**
 * **The** item picker.
 *
 * There were four hand-rolled copies of this in the old editor, each with the
 * same `toLowerCase().includes()` filter written out again, and the create-item
 * modal wired up twice. One control, used everywhere.
 */
function ItemPicker({ label, value, items, onPick, className }) {
  const [query, setQuery] = useState('');
  const [modalOpen, setModalOpen] = useState(false);

  const matches = query.trim()
    ? Object.values(items).filter((i) => (i.name || '').toLowerCase().includes(query.trim().toLowerCase())).slice(0, 5)
    : [];
  const exactExists = Object.values(items).some(
    (i) => (i.name || '').toLowerCase() === query.trim().toLowerCase()
  );

  return (
    <Field label={label} className={className}>
      {value ? (
        <div className="flex items-center gap-1.5">
          <span className="flex-1 truncate text-[11px] text-gray-300">{items[value]?.name || value}</span>
          <button
            onClick={() => onPick('')}
            className="text-gray-600 hover:text-red-400"
            style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 0, lineHeight: 0 }}
          >
            <X size={11} />
          </button>
        </div>
      ) : (
        <div className="relative">
          <Search size={11} className="absolute left-2 top-1/2 -translate-y-1/2 text-gray-600" />
          <input
            type="text"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Search items…"
            className="w-full pl-6"
            style={{ fontSize: 11 }}
          />
        </div>
      )}

      {!value && query.trim() && (
        <div className="mt-1 space-y-1">
          {matches.map((i) => (
            <button
              key={i.id}
              onClick={() => { onPick(i.id); setQuery(''); }}
              className="w-full text-left px-2 py-1 rounded text-[11px] text-gray-300 hover:bg-white/5"
              style={{ background: 'transparent', border: 'none', cursor: 'pointer' }}
            >
              {i.name}
            </button>
          ))}
          {!exactExists && (
            <button
              onClick={() => setModalOpen(true)}
              className="w-full flex items-center gap-1 px-2 py-1 rounded text-[11px] font-bold"
              style={{ background: 'var(--color-accent-muted)', color: 'var(--color-accent-hover)', border: 'none', cursor: 'pointer' }}
            >
              <Plus size={11} /> Create “{query.trim()}”
            </button>
          )}
        </div>
      )}

      <InlineItemModal
        isOpen={modalOpen}
        initialName={query.trim()}
        onClose={() => setModalOpen(false)}
        onCreated={(id) => { onPick(id); setQuery(''); }}
      />
    </Field>
  );
}

/** A list of `{itemId, quantity}` entries — upkeep, and both sides of Converts. */
function ItemList({ label, entries, items, onChange }) {
  return (
    <div>
      {label && (
        <label className="text-[10px] font-bold uppercase tracking-wider block mb-1.5 text-gray-500">{label}</label>
      )}
      <div className="space-y-1.5">
        {entries.map((entry, i) => (
          <div key={i} className="flex items-center gap-1.5">
            <span className="flex-1 text-[11px] text-gray-300 truncate">
              {items[entry.itemId]?.name || entry.itemId}
            </span>
            <input
              type="number" min={1} value={entry.quantity ?? 1}
              onChange={(e) => onChange(entries.map((x, idx) => (idx === i ? { ...x, quantity: Math.max(1, Number(e.target.value)) } : x)))}
              className="w-16" style={{ fontSize: 11, padding: '3px 6px' }}
            />
            <button
              onClick={() => onChange(entries.filter((_, idx) => idx !== i))}
              className="text-gray-600 hover:text-red-400"
              style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 0, lineHeight: 0 }}
            >
              <X size={11} />
            </button>
          </div>
        ))}
      </div>
      <ItemPicker
        label=""
        value=""
        items={items}
        onPick={(itemId) => itemId && onChange([...entries, { itemId, quantity: 1 }])}
      />
    </div>
  );
}

/** Every capability tag the content actually uses — provided, or required. */
function useCapabilityVocabulary(tokens) {
  return useMemo(() => {
    const tags = new Set();
    for (const t of Object.values(tokens)) {
      for (const p of providedTagsOf(t)) if (p.tag) tags.add(p.tag);
      for (const r of t.acceptedTokens || []) if (r?.tag) tags.add(r.tag);
    }
    return [...tags].sort();
  }, [tokens]);
}

/**
 * A Token's provided capabilities, read the way the game reads them.
 *
 * ⚠️ The old editor typed its own list — `['pickaxe','axe','hammer','anvil',
 * 'saw','furnace','pie_tin','cookbook']` — straight into the component. That is
 * exactly the hand-maintained CMS vocabulary CMS-5 exists to forbid, and it had
 * already drifted from the content.
 */
function providedTagsOf(token) {
  const out = [];
  const defaultTier = token?.tier || 1;
  for (const s of statementsOf(token)) {
    if (s?.keyword === KEYWORD.ACTS_AS && s.payload?.tag) {
      out.push({ tag: s.payload.tag, tier: s.payload.tier || defaultTier });
    }
  }
  for (const p of token?.provides || []) {
    if (typeof p === 'string') out.push({ tag: p, tier: defaultTier });
    else if (p?.tag) out.push({ tag: p.tag, tier: p.tier || defaultTier });
  }
  return out;
}

function CapabilityDatalist({ capabilities }) {
  return (
    <datalist id="cms-capability-tags">
      {capabilities.map((c) => <option key={c} value={c} />)}
    </datalist>
  );
}
