import { useMemo, useState } from 'react';
import {
  Plus, X, Trash2, Search, ArrowUp, ArrowDown, Zap, Wrench, Package,
  Gauge, Truck, Repeat, HandCoins, Ban, Sparkles, Factory
} from 'lucide-react';
import { useEntityStore } from '../../stores/useEntityStore';
import { Library, Pencil } from 'lucide-react';
import {
  KEYWORD, KEYWORDS, getKeyword, makeStatement,
  statementsOf, slotsOf, costSlots,
  getPaletteEntry,
  effectRefsOf, expandBearer, rulesLinesOf,
  scaleStatement, effectTitle, MAX_SCALE,
} from '../../utils/constants';
import { Field } from '../shared/EditorLayout';
import RulesLine, { RulesPanel } from './RulesLine';
import InlineItemModal from '../shared/InlineItemModal';

/**
 * The Rules editor — a Token's statements, one sentence per row.
 *
 * ## What this replaced
 * `EffectBlocks.jsx`: 1,080 lines in which five unrelated mechanics — target,
 * capability provision, trigger, upkeep and a *list* of modifiers — shared one
 * container, all five visible on every block whether or not they applied. About
 * 490 of those lines were that crowding, and another 190 were four separate
 * hand-rolled item pickers.
 *
 * Here a row shows only what its keyword needs, and there is one item picker.
 *
 * ## The row IS the sentence
 * Every row ends with its own rules text, generated by the same function the
 * game's tooltip uses. That is the validation: if the sentence says something
 * you did not mean, the rule says something you did not mean. A flipped sign
 * reads "5% **more** work time"; a tag typo reads "adjacent **Coste** Tokens".
 *
 * ## ⚠️ Requires is a view of `acceptedTokens`, not a statement
 * Owner decision Q5. That field gates whether a station produces anything at
 * all — `RecipeResolver.checkAcceptedTokens` is the highest-consequence reader
 * in the system — so it stays exactly where it is and only its presentation
 * moves into this list. The author sees one unified set of sentences; the
 * engine sees no change whatsoever.
 */

const KEYWORD_ICON = {
  [KEYWORD.PROVIDES]: Gauge,
  [KEYWORD.GRANTS]: HandCoins,
  [KEYWORD.ACTS_AS]: Wrench,
  [KEYWORD.REQUIRES]: Package,
  [KEYWORD.RESTOCKS]: Truck,
  [KEYWORD.CONVERTS]: Repeat,
  [KEYWORD.CANNOT]: Ban,
  [KEYWORD.APPLIES]: Sparkles,
  [KEYWORD.STATION]: Factory,
};

/**
 * The statement rows for ONE library entry.
 *
 * Bearer-agnostic on purpose: an entry is a name and a list of sentences, and
 * nothing about editing that list depends on whether a Token or an item ends up
 * referencing it. `Requires` is deliberately absent from the add menu — it is a
 * view of a Token's own `acceptedTokens` field (owner Q5), which is a property
 * of that Token and not something a shared effect could carry.
 */
/**
 * @param {object} [cursor] / [onCursor]  a cursor held by the caller, so several
 *   lists on one screen share ONE panel (Rules Line P6). Omitted, the list keeps
 *   its own. `onCursor` takes a value or a function of this list's cursor.
 * @param {'always'|'focused'} [panel]  `focused` shows the panel only while this
 *   list holds the cursor — a Token's rules are several lists, and a panel per
 *   list would be several idle panels.
 * @param {boolean} [canAdd]  offer "Add rule"
 * @param {boolean} [lockKeyword]  the verb cannot be retyped (Requires)
 * @param {(statement) => React.ReactNode} [rowNote]  a line under each row
 * @param {string|null} [emptyNote]  what an empty list says
 */
export function StatementList({
  statements, onChange, content,
  cursor: heldCursor, onCursor, panel = 'always', canAdd = true, lockKeyword = false,
  rowNote = null,
  emptyNote = 'This effect has a name and nothing behind it. A named effect must carry at least one rule — add one below, or delete the effect.',
}) {
  const storeTokens = useEntityStore((s) => s.tokens);
  const storeItems = useEntityStore((s) => s.items);
  const storeEffects = useEntityStore((s) => s.effects);
  /**
   * ⚠️ `content` lets a caller supply the vocabulary instead of the store.
   *
   * The CMS store PERSISTS itself to localStorage, so anything put into it —
   * even briefly, even to try an editor out — becomes part of the author's
   * workspace and can reach `data/` through the next sync. A sandbox or a test
   * passes its own tokens, items and effects here and never writes a thing.
   */
  const tokens = content?.tokens ?? storeTokens;
  const items = content?.items ?? storeItems;
  const effects = content?.effects ?? storeEffects;
  /**
   * ⚠️ Creating an item WRITES to the persisted store — the same reason
   * `content` exists. A list given its own vocabulary is a sandbox or a test,
   * so it offers no "Create …" anywhere: not in the panel's search, and not
   * in the conversion table's or the upkeep list's item pickers either.
   */
  const canCreate = !content;
  const capabilities = useCapabilityVocabulary(tokens);
  const ctx = useMemo(() => ({ tokens, items, capabilities, effects }), [tokens, items, capabilities, effects]);
  const [menuOpen, setMenuOpen] = useState(false);

  /**
   * ⭐ **One cursor for the whole list**, because there is one panel (E-5).
   *
   * `{ statementId, slotId, occurrence, mode, query, active, moved }` — which
   * rule, which word (by slot and which occurrence of it), and whether it is
   * being retyped (`retype`), holding keyboard focus without a typing box
   * (`word`), or just shown in the panel (`panel`). Functional updates
   * throughout, so a blur arriving after a Tab can never clobber the word Tab
   * just moved to.
   */
  const [ownCursor, setOwnCursor] = useState(null);
  const held = typeof onCursor === 'function';
  const cursor = held ? (heldCursor ?? null) : ownCursor;
  const setCursor = held ? onCursor : setOwnCursor;
  // A name typed into an item search that is being created: `{ statementId, slotId, name }`.
  const [creating, setCreating] = useState(null);
  const actionsFor = (statementId) => {
    const mine = (c) => c && c.statementId === statementId;
    const idle = { mode: 'panel', query: '', active: 0, moved: false };
    return {
      set: (target) => setCursor({ statementId, occurrence: 0, query: '', active: 0, moved: false, ...target }),
      query: (q) => setCursor((c) => (mine(c) ? { ...c, query: q, active: 0, moved: false } : c)),
      move: (step, length) => setCursor((c) => (mine(c)
        ? { ...c, active: Math.max(0, Math.min(length - 1, (c.moved ? c.active : 0) + step)), moved: true }
        : c)),
      close: () => setCursor((c) => (mine(c) ? { ...c, ...idle } : c)),
      closeIf: (slotId, occurrence) => setCursor((c) => (
        mine(c) && c.mode === 'retype' && c.slotId === slotId && (c.occurrence ?? 0) === occurrence
          ? { ...c, ...idle }
          : c
      )),
    };
  };

  const list = statements || [];
  const patch = (id, changes) =>
    onChange(list.map((st) => (st.id === id ? { ...st, ...changes } : st)));
  const remove = (id) => onChange(list.filter((st) => st.id !== id));
  const move = (id, by) => {
    const from = list.findIndex((st) => st.id === id);
    const to = from + by;
    if (from < 0 || to < 0 || to >= list.length) return;
    const next = [...list];
    const [row] = next.splice(from, 1);
    next.splice(to, 0, row);
    onChange(next);
  };

  /**
   * ⚠️ `effect` is here because the line reads it. Without it, picking "Poison"
   * from a blank committed the right effect and then printed "Applies effect_1"
   * — the id, not the name the author just chose — which is the one thing a
   * search exists to avoid (found in the browser, Rules Line P3).
   */
  const names = useMemo(() => ({
    token: (id) => tokens[id]?.name || id,
    item: (id) => items[id]?.name || id,
    effect: (id) => effects?.[id]?.name || id,
  }), [tokens, items, effects]);

  // What the panel is looking at: the focused rule, and the slot in it — a word
  // in the sentence, or one in the cost strip beside it (P5).
  const focusedStatement = cursor ? list.find((st) => st.id === cursor.statementId) || null : null;
  const panelSlot = focusedStatement
    ? [...slotsOf(focusedStatement, ctx), ...costSlots(focusedStatement)].find((sl) => sl.id === cursor.slotId) || null
    : null;

  return (
    /*
      ⭐ The panel on the LEFT, one for every rule (E-5, P0's approved layout).
      ⚠️ It wraps above the rules when the editor column is too narrow for
      both side by side — the reason the V3 editor put its panel beneath the
      line was a fixed sidebar overlapping the chips in a narrow column.
    */
    <div data-rules-editor style={{ display: 'flex', flexWrap: 'wrap', gap: 16, alignItems: 'flex-start' }}>
      {(panel === 'always' || cursor) && (
      <aside
        data-rules-panel-column
        style={{ flex: '0 0 260px', position: 'sticky', top: 12, maxHeight: 'calc(100vh - 48px)', overflowY: 'auto' }}
      >
        <RulesPanel
          slot={panelSlot}
          cursor={focusedStatement ? cursor : null}
          statement={focusedStatement}
          onPatch={(changes) => focusedStatement && patch(focusedStatement.id, changes)}
          onPickRetyped={(value) => {
            if (!focusedStatement || !panelSlot) return;
            patch(focusedStatement.id, panelSlot.patch(value));
            actionsFor(focusedStatement.id).close();
          }}
          onCreate={canCreate && focusedStatement && panelSlot
            ? (name) => setCreating({ statementId: focusedStatement.id, slotId: panelSlot.id, name })
            : null}
        />
      </aside>
      )}

      {/* The item-creation dialog the retired item picker opened, now opened from the panel. */}
      <InlineItemModal
        isOpen={!!creating}
        initialName={creating?.name || ''}
        onClose={() => setCreating(null)}
        onCreated={(id) => {
          const target = list.find((st) => st.id === creating?.statementId);
          const slot = target && slotsOf(target, ctx).find((sl) => sl.id === creating.slotId);
          if (target && slot) {
            patch(target.id, slot.patch(id));
            actionsFor(target.id).close();
          }
          setCreating(null);
        }}
      />

      <div className="space-y-3" style={{ flex: '1 1 420px', minWidth: 0 }}>
      {list.length === 0 && emptyNote && (
        <p className="text-[11px] leading-relaxed" style={{ color: 'var(--color-warning)' }}>
          {emptyNote}
        </p>
      )}

      {list.map((statement, i) => (
        <StatementRow
          key={statement.id}
          statement={statement}
          tokens={tokens}
          items={items}
          names={names}
          ctx={ctx}
          cursor={cursor?.statementId === statement.id ? cursor : null}
          actions={actionsFor(statement.id)}
          canCreate={canCreate}
          lockKeyword={lockKeyword}
          note={rowNote ? rowNote(statement) : null}
          canMoveUp={i > 0}
          canMoveDown={i < list.length - 1}
          onMove={(by) => move(statement.id, by)}
          onChange={(changes) => patch(statement.id, changes)}
          onRemove={() => remove(statement.id)}
        />
      ))}

      {canAdd && <div className="pt-1">
        {menuOpen ? (
          <div className="rounded-lg border border-white/10 bg-black/30 p-2 space-y-1">
            {KEYWORDS.filter((k) => k.id !== KEYWORD.REQUIRES).map((k) => {
              const Icon = KEYWORD_ICON[k.id] || Zap;
              return (
                <button
                  key={k.id}
                  onClick={() => { setMenuOpen(false); onChange([...list, makeStatement(k.id)]); }}
                  className="w-full text-left flex items-start gap-2 px-2 py-1.5 rounded hover:bg-white/5"
                  style={{ background: 'transparent', border: 'none', cursor: 'pointer' }}
                >
                  <Icon size={13} className="text-emerald-400 mt-0.5 flex-shrink-0" />
                  <span className="flex-1">
                    <span className="block text-xs text-gray-200 font-medium">{k.label}</span>
                    <span className="block text-[10px] text-gray-500 leading-snug">{k.blurb}</span>
                  </span>
                </button>
              );
            })}
            <button
              onClick={() => setMenuOpen(false)}
              className="w-full text-center text-[10px] text-gray-500 py-1"
              style={{ background: 'transparent', border: 'none', cursor: 'pointer' }}
            >
              cancel
            </button>
          </div>
        ) : (
          <button
            onClick={() => setMenuOpen(true)}
            className="flex items-center gap-1 px-2.5 py-1.5 rounded text-[11px]"
            style={{ background: 'var(--color-accent-muted)', color: 'var(--color-accent-hover)', border: 'none', cursor: 'pointer' }}
          >
            <Plus size={12} /> Add rule
          </button>
        )}
      </div>}
      </div>
    </div>
  );
}

/**
 * A Token's rules: its requirements, and the library entries it references.
 *
 * ## ⚠️ The rules are NOT edited here any more (Unified Effects P1)
 * A Token points at named effects, and an effect can be pointed at by several
 * Tokens and — from P4 — by items. Editing a sentence in place on one Token
 * would change it everywhere while looking local, which is the one way this
 * feature could hurt. So a row here shows the effect's name and its sentences
 * read-only, with the reference count that says how far an edit reaches, and
 * "Edit" opens the entry itself.
 *
 * `Requires` stays a Token field and stays editable here — it is
 * `acceptedTokens`, which gates whether the station produces anything at all.
 */
export default function Statements({ token, item }) {
  // One component, either bearer (Unified Effects P4). The rules half is
  // identical for a Token and an item — a named effect referenced by id, shown
  // with its sentences and its reference count. What differs is `Requires`,
  // which is a Token field (`acceptedTokens`, owner Q5) and has no meaning on
  // something a hero carries.
  const record = token || item;
  const collectionKey = token ? 'tokens' : 'items';
  const effects = useEntityStore((s) => s.effects);
  const tokens = useEntityStore((s) => s.tokens);
  const items = useEntityStore((s) => s.items);
  const updateToken = useEntityStore((s) => s.updateToken);
  const addEffectForBearer = useEntityStore((s) => s.addEffectForBearer);
  const addEffectRef = useEntityStore((s) => s.addEffectRef);
  const removeEffectRef = useEntityStore((s) => s.removeEffectRef);
  const setEffectRefScale = useEntityStore((s) => s.setEffectRefScale);
  const setEffectStatements = useEntityStore((s) => s.setEffectStatements);
  const setActiveEntity = useEntityStore((s) => s.setActiveEntity);

  const [menuOpen, setMenuOpen] = useState(false);
  const [browsing, setBrowsing] = useState(false);
  const [search, setSearch] = useState('');

  /**
   * ⭐ **One cursor across every rule on this bearer**, so ONE panel shows at a
   * time (E-5) although the rules are several lists — one per effect, plus the
   * Requires rows. `{ listId, cursor }`; each list sees only its own share.
   */
  const [held, setHeld] = useState(null);
  const cursorFor = (listId) => ({
    cursor: held?.listId === listId ? held.cursor : null,
    onCursor: (update) => setHeld((prev) => {
      const mine = prev?.listId === listId ? prev.cursor : null;
      const next = typeof update === 'function' ? update(mine) : update;
      if (next === mine) return prev;
      if (next) return { listId, cursor: next };
      return prev?.listId === listId ? null : prev;
    }),
  });

  const requirements = token ? (token.acceptedTokens || []) : [];
  const refs = effectRefsOf(record);
  const setRequirements = (next) => updateToken(record.id, { acceptedTokens: next });

  // ⚠️ `effect` too: without it an Applies rule printed the effect's id (found in P3).
  const names = useMemo(() => ({
    token: (id) => tokens[id]?.name || id,
    item: (id) => items[id]?.name || id,
    effect: (id) => effects?.[id]?.name || id,
  }), [tokens, items, effects]);

  /**
   * How many bearers use an entry — the number that makes an edit legible.
   * Counts Tokens AND items: an effect shared between a Bay and a potion is
   * exactly the case the library exists for, and an edit reaches both.
   */
  const bearerCount = (effectId) =>
    [...Object.values(tokens), ...Object.values(items)]
      .filter((b) => effectRefsOf(b).some((r) => r.effectId === effectId)).length;

  const unused = Object.values(effects)
    .filter((e) => !refs.some((r) => r.effectId === e.id))
    .filter((e) => !search || (e.name || '').toLowerCase().includes(search.toLowerCase()));

  const isEmpty = refs.length === 0 && requirements.length === 0;

  if (!record) return null;

  return (
    <div className="space-y-3">
      {isEmpty && (
        <p className="text-[11px] text-gray-500 leading-relaxed">
          {token
            ? 'No rules. A pure producer needs none — rules are for Tokens that change what happens around them, hand a capability to a neighbour, or need one themselves.'
            : 'No rules. Most items need none — rules are for gear and consumables that change what their hero does: the Token they are working, the enemy they are fighting, or the hero themselves.'}
        </p>
      )}

      {token?.effectBlocks?.length > 0 && (
        <div
          className="rounded-lg p-3 text-[11px] leading-relaxed"
          style={{ background: 'rgba(255,180,0,0.08)', border: '1px solid rgba(255,180,0,0.3)', color: 'var(--color-warning)' }}
        >
          This Token still carries <strong>effect blocks</strong> from the old
          editor. They are not read by the game any more, so it currently does
          nothing. Rebuild its rules below — adding the first rule clears the old
          data for good.
        </div>
      )}

      {/*
        ⭐ Requires on the Rules Line (P6). Still a view of `acceptedTokens`
        (owner Q5): each entry is shown as a Requires sentence and written back
        as the plain `{ tag, minTier }` it was. The verb is locked, so it cannot
        be retyped into a rule, and it has no cost strip, since nothing spends.
      */}
      {requirements.length > 0 && (
        <StatementList
          statements={requirements.map((req, i) => ({ id: `req_${i}`, keyword: KEYWORD.REQUIRES, payload: req }))}
          onChange={(next) => setRequirements(next.map((st) => st.payload))}
          {...cursorFor('requires')}
          panel="focused"
          canAdd={false}
          lockKeyword
          emptyNote={null}
          rowNote={(st) => <RequiresNote requirement={st.payload} tokens={tokens} />}
        />
      )}

      {refs.map(({ effectId, scale }) => {
        const entry = effects[effectId];

        if (!entry) {
          return (
            <div
              key={effectId}
              className="rounded-lg p-3 text-[11px] leading-relaxed flex items-center gap-2"
              style={{ background: 'rgba(255,80,80,0.08)', border: '1px solid rgba(255,80,80,0.3)', color: '#f87171' }}
            >
              <span className="flex-1">
                This Token points at the effect <strong>{effectId}</strong>, which no
                longer exists. It currently has no rule from it.
              </span>
              <button
                onClick={() => removeEffectRef(collectionKey, record.id, effectId)}
                className="btn-ghost" style={{ padding: '2px 6px' }}
              >
                <Trash2 size={12} />
              </button>
            </div>
          );
        }

        // Scalable when at least one of its statements declares a field a scale
        // touches — the palette for a Provides/Grants/Converts payload, the
        // keyword itself for Applies (UE-7).
        const scalable = (entry.statements || []).some((st) =>
          getPaletteEntry(st?.payload?.type)?.scales || getKeyword(st?.keyword)?.scales
        );
        const count = bearerCount(effectId);
        /**
         * ⭐ **Owner ruling 2026-09-12 (P6): edited in place only when not shared.**
         * An effect only this bearer uses — the usual case, since "New rule"
         * makes one — gets the full Rules Line here. A shared one stays
         * read-only with its count and Edit, because an in-place edit would
         * change every other bearer while looking local (Unified Effects P1).
         */
        const editable = count <= 1;
        /**
         * ⚠️ The sentences are rendered from the **scaled** statements, not the
         * entry's own. A row showing "5% less work time" beside a scale of 3 is
         * the drift UE-8 exists to prevent — the words have to say what this
         * bearer actually does, which is 15%.
         */
        const lines = rulesLinesOf(
          { statements: (entry.statements || []).map((st) => scaleStatement(st, scale)) },
          names
        );

        return (
          <div key={effectId} className="rounded-lg border border-white/10 bg-black/20">
            <div className="flex items-center gap-2 px-3 py-2 border-b border-white/5">
              <Library size={13} className="text-emerald-400" />
              <span className="text-xs font-medium text-gray-200">{effectTitle(entry.name, scale)}</span>
              {count > 1 && (
                <span
                  className="text-[10px] px-1.5 py-0.5 rounded"
                  style={{ background: 'var(--color-accent-muted)', color: 'var(--color-accent-hover)' }}
                  title={`Shared with ${count - 1} other Token${count > 2 ? 's' : ''} — editing it changes all of them`}
                >
                  shared x{count}
                </span>
              )}
              <span className="flex-1" />
              {/*
                Scale lives on the REFERENCE (UE-6): the one thing a bearer may
                vary about a shared effect. Offered only where the effect has
                something to scale — `Acts as` and `Cannot` declare nothing, and
                a spinner that changed no number would be a lie.
              */}
              {scalable && (
                <label className="flex items-center gap-1 text-[10px] text-gray-500" title="How strong this Token's version is. 1-5; the entry itself is unchanged.">
                  x
                  <input
                    type="number"
                    min={1}
                    max={MAX_SCALE}
                    step={1}
                    value={scale}
                    onChange={(e) => setEffectRefScale(collectionKey, record.id, effectId, e.target.value)}
                    className="w-11"
                    style={{ fontSize: 10, padding: '1px 4px' }}
                  />
                </label>
              )}
              <button
                onClick={() => setActiveEntity(effectId, 'effect')}
                className="btn-ghost flex items-center gap-1 text-[10px]"
                style={{ padding: '2px 6px' }}
                title="Open this effect"
              >
                <Pencil size={11} /> Edit
              </button>
              <button
                onClick={() => removeEffectRef(collectionKey, record.id, effectId)}
                className="btn-ghost" style={{ padding: '2px 6px' }}
                title="Stop this Token using the effect (the effect itself is kept)"
              >
                <X size={12} />
              </button>
            </div>
            {editable ? (
              <div className="px-3 py-2 space-y-2" data-editable-effect={effectId}>
                {scale > 1 && (
                  <p className="text-[10px] leading-relaxed" style={{ color: 'var(--color-accent-hover)' }}>
                    This {token ? 'Token' : 'item'} carries it at x{scale}. The numbers below are the
                    effect’s own; the game multiplies them.
                  </p>
                )}
                <StatementList
                  statements={entry.statements || []}
                  onChange={(next) => setEffectStatements(effectId, next)}
                  {...cursorFor(effectId)}
                  panel="focused"
                  canAdd={false}
                  emptyNote="This effect has no rule left. Open it to add one, or remove it from here."
                />
              </div>
            ) : (
              <div className="px-3 py-2 space-y-1" data-shared-effect={effectId}>
                {lines.length === 0 ? (
                  <p className="text-[11px] italic" style={{ color: 'var(--color-warning)' }}>
                    This effect has no rule behind it.
                  </p>
                ) : lines.map((line, i) => (
                  <p key={i} className="text-[11px] text-gray-400 leading-relaxed">{line}</p>
                ))}
              </div>
            )}
          </div>
        );
      })}

      <div className="pt-1 space-y-2">
        {browsing && (
          <div className="rounded-lg border border-white/10 bg-black/30 p-2 space-y-1">
            <div className="flex items-center gap-1.5 px-1 pb-1">
              <Search size={12} className="text-gray-500" />
              <input
                autoFocus
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                placeholder="Search effects..."
                className="flex-1 bg-transparent text-xs text-gray-200 outline-none"
              />
            </div>
            {unused.length === 0 ? (
              <p className="text-[10px] text-gray-600 px-2 py-1">No other effects to add.</p>
            ) : unused.map((e) => (
              <button
                key={e.id}
                onClick={() => { setBrowsing(false); setSearch(''); addEffectRef(collectionKey, record.id, e.id); }}
                className="w-full text-left flex items-start gap-2 px-2 py-1.5 rounded hover:bg-white/5"
                style={{ background: 'transparent', border: 'none', cursor: 'pointer' }}
              >
                <Library size={12} className="text-emerald-400 mt-0.5 flex-shrink-0" />
                <span className="flex-1">
                  <span className="block text-xs text-gray-200 font-medium">{e.name}</span>
                  <span className="block text-[10px] text-gray-500 leading-snug">
                    {rulesLinesOf(e, names)[0] || 'No rule behind it yet.'}
                  </span>
                </span>
                <span className="text-[10px] text-gray-600 mt-0.5">
                  {bearerCount(e.id) > 0 ? `used x${bearerCount(e.id)}` : 'unused'}
                </span>
              </button>
            ))}
            <button
              onClick={() => { setBrowsing(false); setSearch(''); }}
              className="w-full text-center text-[10px] text-gray-500 py-1"
              style={{ background: 'transparent', border: 'none', cursor: 'pointer' }}
            >
              cancel
            </button>
          </div>
        )}

        {menuOpen ? (
          <div className="rounded-lg border border-white/10 bg-black/30 p-2 space-y-1">
            {KEYWORDS.filter((k) => token || k.id !== KEYWORD.REQUIRES).map((k) => {
              const Icon = KEYWORD_ICON[k.id] || Zap;
              return (
                <button
                  key={k.id}
                  onClick={() => {
                    setMenuOpen(false);
                    // Requires is a Token field, not a shared effect (owner Q5).
                    if (k.id === KEYWORD.REQUIRES) {
                      setRequirements([...requirements, { tag: '', minTier: 1 }]);
                      return;
                    }
                    addEffectForBearer(collectionKey, record.id, k.id);
                  }}
                  className="w-full text-left flex items-start gap-2 px-2 py-1.5 rounded hover:bg-white/5"
                  style={{ background: 'transparent', border: 'none', cursor: 'pointer' }}
                >
                  <Icon size={13} className="text-emerald-400 mt-0.5 flex-shrink-0" />
                  <span className="flex-1">
                    <span className="block text-xs text-gray-200 font-medium">{k.label}</span>
                    <span className="block text-[10px] text-gray-500 leading-snug">{k.blurb}</span>
                  </span>
                </button>
              );
            })}
            <button
              onClick={() => setMenuOpen(false)}
              className="w-full text-center text-[10px] text-gray-500 py-1"
              style={{ background: 'transparent', border: 'none', cursor: 'pointer' }}
            >
              cancel
            </button>
          </div>
        ) : (
          <div className="flex gap-2">
            <button
              onClick={() => setMenuOpen(true)}
              className="flex items-center gap-1 px-2.5 py-1.5 rounded text-[11px]"
              style={{ background: 'var(--color-accent-muted)', color: 'var(--color-accent-hover)', border: 'none', cursor: 'pointer' }}
            >
              <Plus size={12} /> New rule
            </button>
            <button
              onClick={() => setBrowsing(true)}
              className="flex items-center gap-1 px-2.5 py-1.5 rounded text-[11px] btn-ghost"
            >
              <Library size={12} /> Use an existing effect
            </button>
          </div>
        )}
      </div>
    </div>
  );
}

/** One row's chrome: keyword name, reorder, delete. */
function RowShell({ keywordId, onMove, canMoveUp, canMoveDown, onRemove, children }) {
  const keyword = getKeyword(keywordId);
  const Icon = KEYWORD_ICON[keywordId] || Zap;
  return (
    <div className="rounded-lg border border-white/10 bg-black/20">
      <div className="flex items-center gap-2 px-3 py-2 border-b border-white/5">
        <Icon size={13} className="text-emerald-400" />
        <span className="text-xs font-medium text-gray-200">{keyword?.label || keywordId}</span>
        <span className="flex-1" />
        {onMove && (
          <>
            <button
              onClick={() => onMove(-1)}
              disabled={!canMoveUp}
              className="text-gray-600 hover:text-gray-300 disabled:opacity-20"
              style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 0, lineHeight: 0 }}
              title="Move up"
            >
              <ArrowUp size={12} />
            </button>
            <button
              onClick={() => onMove(1)}
              disabled={!canMoveDown}
              className="text-gray-600 hover:text-gray-300 disabled:opacity-20"
              style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 0, lineHeight: 0 }}
              title="Move down"
            >
              <ArrowDown size={12} />
            </button>
          </>
        )}
        <button
          onClick={onRemove}
          className="text-gray-600 hover:text-red-400"
          style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 0, lineHeight: 0 }}
          title="Remove rule"
        >
          <Trash2 size={12} />
        </button>
      </div>

      {/*
        A row shows its sentence once, as the line itself — the quoted copy that
        used to sit under Requires went when Requires got a line (P6).
      */}
      <div className="p-3 space-y-2.5">{children}</div>
    </div>
  );
}

/**
 * Which Tokens satisfy a requirement — the one thing the retired Requires form
 * showed that its sentence does not say.
 */
function RequiresNote({ requirement, tokens }) {
  const effects = useEntityStore((s) => s.effects);
  // Expanded: an `Acts as` rule lives in the library, so an unexpanded Token
  // provides nothing and this list would always read "nothing supplies this".
  const providers = Object.values(tokens).filter((t) =>
    providedTagsOf(expandBearer(t, effects || {}))
      .some((p) => p.tag === requirement.tag && (p.tier || 1) >= (requirement.minTier || 1))
  );
  return (
    <p className="text-[10px] text-gray-500" data-satisfied-by>
      Satisfied by:{' '}
      {providers.length === 0 ? (
        <span className="text-amber-400">nothing yet — this Token can never work</span>
      ) : (
        providers.map((t) => t.name).join(', ')
      )}
    </p>
  );
}
/**
 * One real statement, edited as a **sentence** (G-18).
 *
 * ⚠️ **The nested pickers are gone.** This row used to stack a payload box, a
 * role picker, a reach picker, a filter picker and a trigger clause, each in its
 * own labelled section — the "many nested dropdown menus" the owner asked to be
 * rid of. Every one of them was an expression of the same thing: the slots of a
 * statement. `statementSlots.js` describes those slots once, and `RulesLine`
 * renders the rule as the sentence it is, with its decision words clickable.
 *
 * ⚠️ **Retired in the same commit rather than left beside it.** Two editors for
 * one thing is the duplication this project keeps deleting, and a form that can
 * drift from the sentence is the exact drift UE-8 exists to prevent.
 *
 * What survives beneath it: a conversion's item table (E-8), and the cost strip
 * (E-6, P5) — the charge cost and the upkeep, which the sentence never says —
 * with the upkeep's items as a small table under that.
 */
function StatementRow({ statement, items, names, ctx, cursor, actions, canCreate, lockKeyword, note, onChange, onRemove, onMove, canMoveUp, canMoveDown }) {
  const keyword = getKeyword(statement.keyword);
  const upkeep = keyword?.upkeep ? statement.upkeep : null;

  return (
    <RowShell
      keywordId={statement.keyword}
      onRemove={onRemove}
      onMove={onMove}
      canMoveUp={canMoveUp}
      canMoveDown={canMoveDown}
    >
      <RulesLine
        statement={statement}
        onChange={onChange}
        names={names}
        ctx={ctx}
        cursor={cursor}
        actions={actions}
        lockKeyword={lockKeyword}
        form={<PayloadFields statement={statement} items={items} canCreate={canCreate} onChange={onChange} />}
        upkeepTable={upkeep && (
          <ItemList
            label="Consumes from the Bank"
            entries={upkeep.items || []}
            items={items}
            canCreate={canCreate}
            onChange={(next) => onChange({ upkeep: { ...upkeep, items: next } })}
          />
        )}
      />
      {note}
    </RowShell>
  );
}

/**
 * ⭐ **The one form that survives the Rules Line** (E-8, P4).
 *
 * A conversion's two item lists are a genuine table — several rows, each with
 * its own quantity — and a five-item exchange written out inline stops being
 * a sentence.
 *
 * ⚠️ **Eight forms were deleted here, not hidden**: Provides (effect, combine,
 * amount, direction, skill), Grants, Works as, Acts as, Restocks, Cannot,
 * Applies and Deals. Every decision they held is a slot in the line now, and
 * `FormFreeSlots.test.js` walks that inventory field by field — because a
 * decision only a form could reach becomes silently unauthorable the day the
 * form goes, and the last code review had already found one.
 */
function PayloadFields({ statement, items, canCreate, onChange }) {
  if (statement.keyword !== KEYWORD.CONVERTS) return null;
  const payload = statement.payload || {};
  const setPayload = (changes) => onChange({ payload: { ...payload, ...changes } });
  return (
    <div className="grid grid-cols-2 gap-3">
      <ItemList
        label="Spends from the Bank"
        entries={payload.consumes || []}
        items={items}
        canCreate={canCreate}
        onChange={(consumes) => setPayload({ consumes })}
      />
      <ItemList
        label="Produces on the board"
        entries={payload.produces || []}
        items={items}
        canCreate={canCreate}
        onChange={(produces) => setPayload({ produces })}
      />
    </div>
  );
}

/**
 * **The** item picker.
 *
 * There were four hand-rolled copies of this in the old editor, each with the
 * same `toLowerCase().includes()` filter written out again, and the create-item
 * modal wired up twice. One control, used everywhere.
 */
function ItemPicker({ label, value, items, onPick, className, canCreate = true }) {
  const [query, setQuery] = useState('');
  const [modalOpen, setModalOpen] = useState(false);

  const matches = query.trim()
    ? Object.values(items).filter((i) => (i.name || '').toLowerCase().includes(query.trim().toLowerCase())).slice(0, 5)
    : [];
  const exactExists = Object.values(items).some(
    (i) => (i.name || '').toLowerCase() === query.trim().toLowerCase()
  );

  return (
    <Field label={label} className={className}>
      {value ? (
        <div className="flex items-center gap-1.5">
          <span className="flex-1 truncate text-[11px] text-gray-300">{items[value]?.name || value}</span>
          <button
            onClick={() => onPick('')}
            className="text-gray-600 hover:text-red-400"
            style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 0, lineHeight: 0 }}
          >
            <X size={11} />
          </button>
        </div>
      ) : (
        <div className="relative">
          <Search size={11} className="absolute left-2 top-1/2 -translate-y-1/2 text-gray-600" />
          <input
            type="text"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Search items…"
            className="w-full pl-6"
            style={{ fontSize: 11 }}
          />
        </div>
      )}

      {!value && query.trim() && (
        <div className="mt-1 space-y-1">
          {matches.map((i) => (
            <button
              key={i.id}
              onClick={() => { onPick(i.id); setQuery(''); }}
              className="w-full text-left px-2 py-1 rounded text-[11px] text-gray-300 hover:bg-white/5"
              style={{ background: 'transparent', border: 'none', cursor: 'pointer' }}
            >
              {i.name}
            </button>
          ))}
          {canCreate && !exactExists && (
            <button
              onClick={() => setModalOpen(true)}
              className="w-full flex items-center gap-1 px-2 py-1 rounded text-[11px] font-bold"
              style={{ background: 'var(--color-accent-muted)', color: 'var(--color-accent-hover)', border: 'none', cursor: 'pointer' }}
            >
              <Plus size={11} /> Create “{query.trim()}”
            </button>
          )}
        </div>
      )}

      <InlineItemModal
        isOpen={modalOpen}
        initialName={query.trim()}
        onClose={() => setModalOpen(false)}
        onCreated={(id) => { onPick(id); setQuery(''); }}
      />
    </Field>
  );
}

/** A list of `{itemId, quantity}` entries — upkeep, and both sides of Converts. */
function ItemList({ label, entries, items, onChange, canCreate = true }) {
  return (
    <div>
      {label && (
        <label className="text-[10px] font-bold uppercase tracking-wider block mb-1.5 text-gray-500">{label}</label>
      )}
      <div className="space-y-1.5">
        {entries.map((entry, i) => (
          <div key={i} className="flex items-center gap-1.5">
            <span className="flex-1 text-[11px] text-gray-300 truncate">
              {items[entry.itemId]?.name || entry.itemId}
            </span>
            <input
              type="number" min={1} value={entry.quantity ?? 1}
              onChange={(e) => onChange(entries.map((x, idx) => (idx === i ? { ...x, quantity: Math.max(1, Number(e.target.value)) } : x)))}
              className="w-16" style={{ fontSize: 11, padding: '3px 6px' }}
            />
            <button
              onClick={() => onChange(entries.filter((_, idx) => idx !== i))}
              className="text-gray-600 hover:text-red-400"
              style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 0, lineHeight: 0 }}
            >
              <X size={11} />
            </button>
          </div>
        ))}
      </div>
      <ItemPicker
        label=""
        value=""
        items={items}
        canCreate={canCreate}
        onPick={(itemId) => itemId && onChange([...entries, { itemId, quantity: 1 }])}
      />
    </div>
  );
}

/**
 * Every capability tag the content actually uses — provided, or required.
 *
 * ⚠️ **Reads through the library** (Unified Effects P1). An `Acts as` rule lives
 * in a named entry now, not on the Token, so walking Tokens alone would return
 * an empty vocabulary and quietly turn every capability suggestion off.
 */
function useCapabilityVocabulary(tokens) {
  const effects = useEntityStore((s) => s.effects);
  return useMemo(() => {
    const tags = new Set();
    for (const t of Object.values(tokens)) {
      for (const p of providedTagsOf(expandBearer(t, effects || {}))) if (p.tag) tags.add(p.tag);
      for (const r of t.acceptedTokens || []) if (r?.tag) tags.add(r.tag);
    }
    return [...tags].sort();
  }, [tokens, effects]);
}

/**
 * A Token's provided capabilities, read the way the game reads them.
 *
 * ⚠️ The old editor typed its own list — `['pickaxe','axe','hammer','anvil',
 * 'saw','furnace','pie_tin','cookbook']` — straight into the component. That is
 * exactly the hand-maintained CMS vocabulary CMS-5 exists to forbid, and it had
 * already drifted from the content.
 */
function providedTagsOf(token) {
  const out = [];
  const defaultTier = token?.tier || 1;
  for (const s of statementsOf(token)) {
    if (s?.keyword === KEYWORD.ACTS_AS && s.payload?.tag) {
      out.push({ tag: s.payload.tag, tier: s.payload.tier || defaultTier });
    }
  }
  for (const p of token?.provides || []) {
    if (typeof p === 'string') out.push({ tag: p, tier: defaultTier });
    else if (p?.tag) out.push({ tag: p.tag, tier: p.tier || defaultTier });
  }
  return out;
}
